### ISSUE TITLE
My app is too big

### ISSUE THREAD

**Issue by yusufquteb** [Sketchware-Pro/Sketchware-Pro#1005]
I use last version of sketchwar 
I made an app with over than 50 pages
Total volume exceed 100mb

When i run the app get this error 

java.lang.OutOfMemoryError: Failed to allocate a 88 byte allocation with 2295953 free bytes and 2242KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at org.eclipse.jdt.internal.compiler.flow.UnconditionalFlowInfo.copy(UnconditionalFlowInfo.java:700)
	at org.eclipse.jdt.internal.compiler.flow.UnconditionalFlowInfo.unconditionalCopy(UnconditionalFlowInfo.java:2154)
	at org.eclipse.jdt.internal.compiler.ast.OR_OR_Expression.analyseCode(OR_OR_Expression.java:67)
	at org.eclipse.jdt.internal.compiler.ast.OR_OR_Expression.analyseCode(OR_OR_Expression.java:61)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:66)
	at org.eclipse.jdt.internal.compiler.ast.Block.analyseCode(Block.java:50)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:141)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:129)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:956)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:252)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.analyseCode(QualifiedAllocationExpression.java:143)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:236)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:129)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:956)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:304)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:136)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:908)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by JavkhlanK** [comment]
You've figured it out already. The project's too heavy for your phone.
