### ISSUE TITLE
I dont know

### ISSUE THREAD

**Issue by Ade-Firmansyah** [Sketchware-Pro/Sketchware-Pro#1017]
**Describe the bug**
Please give us a clear and concise description of what the bug is.

@iyxan23 
java.lang.RuntimeException: Undefined Prefix: ads in com.android.org.kxml2.io.KXmlParser@14ad477
	at com.android.org.kxml2.io.KXmlParser.adjustNsp(KXmlParser.java:260)
	at com.android.org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1153)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at a.a.a.Ox.readAttributesToReplace(Ox.java:873)
	at a.a.a.Ox.writeWidget(Ox.java:239)
	at a.a.a.Ox.writeRootLayout(Ox.java:109)
	at a.a.a.Ox.a(Ox.java:229)
	at a.a.a.yq.getFileSrc(yq.java:881)
	at com.besome.sketch.design.DesignActivity.lambda$showCurrentActivitySrcCode$12$com-besome-sketch-design-DesignActivity(DesignActivity.java:724)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
![Screenshot_2023-10-24-23-04-04-180_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/112641120/f848e7b0-6dff-417d-8df8-ef97aa556424)

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 10]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by JavkhlanK** [comment]
why did you not fill out the template…
