### ISSUE TITLE
Error while compiling (Sketchware version - v6.4.0-rc04-minApi26)

### ISSUE THREAD

**Issue by subompaul** [Sketchware-Pro/Sketchware-Pro#1018]
This error came up in the compile log while compiling.

`com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /data/user/0/com.sketchware.remod/cache/libs/android.jar
	at Version.fakeStackEntry(Version_3.3.28.java:0)
	at com.android.tools.r8.internal.Bj$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:75)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
	at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.D8.run(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
	at mod.jbk.build.compiler.dex.DexCompiler.compileDexFiles(DexCompiler.java:49)
	at a.a.a.Dp.c(Dp.java:233)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1032)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1152)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:895)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.android.tools.r8.internal.Hc: Failed to read 'Landroid/widget/RelativeLayout;
	at com.android.tools.r8.utils.z.getProgramResource(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:122)
	at com.android.tools.r8.internal.Ka.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.La.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.sa.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:8)
	at com.android.tools.r8.internal.sa.get(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
	at com.android.tools.r8.internal.ta.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
	at com.android.tools.r8.graph.B2.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.D$$ExternalSyntheticLambda0.apply(Unknown Source:4)
	at com.android.tools.r8.synthesis.s.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:284)
	at com.android.tools.r8.graph.d.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
	at com.android.tools.r8.graph.d.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.g.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.o2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:260)
	at com.android.tools.r8.internal.o2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.n2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:106)
	at com.android.tools.r8.internal.n2.f(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.graph.k3.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
	at com.android.tools.r8.code.K.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:98)
	at com.android.tools.r8.graph.N.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:121)
	at com.android.tools.r8.graph.N.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:115)
	at com.android.tools.r8.graph.d3.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:11)
	at com.android.tools.r8.internal.o2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:53)
	at com.android.tools.r8.internal.o2.$r8$lambda$fa9WwKoa3GJBx_ORPEpJcJrUT6Q(Unknown Source:0)
	at com.android.tools.r8.internal.o2$$ExternalSyntheticLambda8.accept(Unknown Source:4)
	at com.android.tools.r8.graph.W0.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.W0.$r8$lambda$i2iBsc8RWlzBOBcTiB1rTGDMhEA(Unknown Source:0)
	at com.android.tools.r8.graph.W0$$ExternalSyntheticLambda33.accept(Unknown Source:6)
	at com.android.tools.r8.graph.L2.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:5)
	at com.android.tools.r8.graph.L2.$r8$lambda$yFvp3O8cy1s_MHOS_kF3JySC8eU(Unknown Source:0)
	at com.android.tools.r8.graph.L2$$ExternalSyntheticLambda4.accept(Unknown Source:6)
	at com.android.tools.r8.graph.M2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.M2.$r8$lambda$4vYYJ8_H2NO1axEVtuGPCzexXGY(Unknown Source:0)
	at com.android.tools.r8.graph.M2$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at com.android.tools.r8.graph.K2.g(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.M2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
	at com.android.tools.r8.graph.L2.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.W0.g(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.o2.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:7)
	at com.android.tools.r8.internal.o2$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:39)
	at com.android.tools.r8.utils.C.$r8$lambda$UBg1g3UiNaEyDFkrovkGPiF9oQo(Unknown Source:0)
	at com.android.tools.r8.utils.C$$ExternalSyntheticLambda7.accept(Unknown Source:2)
	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:44)
	at com.android.tools.r8.utils.C.$r8$lambda$X758yd4-wB5iizs77sTzF9Y-yPc(Unknown Source:0)
	at com.android.tools.r8.utils.C$$ExternalSyntheticLambda9.a(Unknown Source:2)
	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:38)
	at com.android.tools.r8.utils.C.$r8$lambda$9m8jv_zBqhOSW4qXJYSSvKW5IK4(Unknown Source:0)
	at com.android.tools.r8.utils.C$$ExternalSyntheticLambda11.call(Unknown Source:6)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Suppressed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Hc: Failed to read 'Landroid/widget/RelativeLayout;
		at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:766)
		at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
		at com.android.tools.r8.D8.$r8$lambda$aRVyB0kFcdZ16P9QfsGc9mHei1I(Unknown Source:0)
		at com.android.tools.r8.D8$$ExternalSyntheticLambda2.run(Unknown Source:6)
		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:24)
		at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
		at com.android.tools.r8.D8.run(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
		at mod.jbk.build.compiler.dex.DexCompiler.compileDexFiles(DexCompiler.java:49)
		at a.a.a.Dp.c(Dp.java:233)
		at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1032)
		at a.a.a.MA.a(Unknown Source:11)
		at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1152)
		at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:895)
		at android.os.AsyncTask$3.call(AsyncTask.java:394)
		at java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
		at java.lang.Thread.run(Thread.java:1012)
	Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Hc: Failed to read 'Landroid/widget/RelativeLayout;
		at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:609)
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:985)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:43)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:41)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:40)
		at com.android.tools.r8.internal.o2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:11)
		at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:750)
		... 18 more
	Caused by: [CIRCULAR REFERENCE: com.android.tools.r8.internal.Hc: Failed to read 'Landroid/widget/RelativeLayout;]
`

What is the solution for this error?
![Screenshot_2023-10-25-13-43-51-026_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/99627749/562ac89f-e0a9-455a-bdcb-8110332fedb9)

**Comment by subompaul** [comment]
Oh when I turned off D8 the error was solved

**Comment by JavkhlanK** [comment]
1. Please use the bug report template next time
2. You used an old version, that's probably why, and there's been quite a few bug fixes since that version.
