### ISSUE TITLE
ListView bind Error

### ISSUE THREAD

**Issue by appt2** [Sketchware-Pro/Sketchware-Pro#1025]
mobile poco x5 pro
version app min api 26 
```shell

java.lang.VerifyError: Verifier rejected class a.a.a.Nw: void a.a.a.Nw.onClick(android.view.View) failed to verify: void a.a.a.Nw.onClick(android.view.View): [0x4F] 'this' argument 'Reference: a.a.a.aB' not instance of 'Reference: android.app.Dialog' (declaration of 'a.a.a.Nw' appears in /data/app/~~Ur1HL3oK_XIJ7rdJaNtFTw==/com.sketchware.remod-78q0WbFMehnbfZZ5JmnoWg==/base.apk)
	at a.a.a.Pw.a(Unknown Source:160)
	at a.a.a.Pw.onClick(Unknown Source:33)
	at android.view.View.performClick(View.java:7556)
	at android.view.View.performClickInternal(View.java:7533)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29663)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by appt2** [comment]
im downloading 
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/6742412438
version min api

**Comment by adesonob** [comment]
When I click on the listview custom list screen to edit the blocks it crashes.

**Comment by adesonob** [comment]
![Screenshot_20231223-203307_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/92691301/1861727c-3eb2-4289-8f83-04238415cbf9)
![Screenshot_20231223-202946_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/92691301/f7dc665d-d9f0-4ac8-b7ed-5f96087fd387)

**Comment by appt2** [comment]
fixed

**Comment by JavkhlanK** [comment]
right, thanks
