### ISSUE TITLE
No such a method or interface: setColorTint

### ISSUE THREAD

**Issue by rexfernandezluciano** [Sketchware-Pro/Sketchware-Pro#1035]
**Describe the bug**
In the editor, via Event tab when you open activity method such as onCreate it will crash the app.

**To Reproduce**
1. Go to Event tab
2. Open onCreate or add any method
3. Done
...

**Expected behavior**
Should not crash the app

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: T03 Acer
 - OS: Android 5.1
 - Sketchware Pro version: rc05-test-build-5-minApi21]

**Additional context**

**Comment by JavkhlanK** [comment]
Sounds like an issue with your Custom Blocks. Can you try renaming the directory `My Block` in /Internal storage/.sketchware/resources/block/ to something else and see if it crashes again?

**Comment by rexfernandezluciano** [comment]
Even, creating a new project, and try to open Event it will crashed.

**Comment by rexfernandezluciano** [comment]
This version has a bug: [Sketchware Pro RC-5 Test Build 5: Unreleased](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/6742412438)

**Comment by JavkhlanK** [comment]
why did you ignore my earlier comment

**Comment by rexfernandezluciano** [comment]
Here the complete error log:

```java.lang.NoSuchMethodError: No interface method setIconTintList(Landroid/content/res/ColorStateList;)Landroid/view/MenuItem; in class Landroid/view/MenuItem; or its super classes (declaration of 'android.view.MenuItem' appears in /system/framework/framework.jar)
	at com.besome.sketch.editor.LogicEditorActivity.onCreateOptionsMenu(LogicEditorActivity.java:1961)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2878)
	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)```

**Comment by rexfernandezluciano** [comment]
java.lang.NoSuchMethodError: No interface method setIconTintList(Landroid/content/res/ColorStateList;)Landroid/view/MenuItem; in class Landroid/view/MenuItem; or its super classes (declaration of 'android.view.MenuItem' appears in /system/framework/framework.jar)
	at com.besome.sketch.editor.LogicEditorActivity.onCreateOptionsMenu(LogicEditorActivity.java:1961)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2878)
	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by JavkhlanK** [comment]
You're not using v6.4.0-rc05 according to that stack trace. I'll create a proper bug report instead, but thanks for reporting
