### ISSUE TITLE
Sketchware crashes 

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1059]
![Screenshot_20240110_215402_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/012fd8ce-f153-4013-bde0-824a16585302)

When I change the width, height, scale or change image, Sketchware crashes

Version v6.4.0-SNAPSHOT-be51bbb-minApi26

**Comment by JavkhlanK** [comment]
1. Show the entire error message
2. Are you talking about ImageView? Please add more details, all you've entered so far is ambiguous.

**Comment by TanTai97o** [comment]
Yes,this error of ImageView

![Screenshot_20240110_215402_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/0dd88388-f840-4b2c-8396-b9f1f2112e20)
![Screenshot_20240111_005208_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/abe36599-7d05-436a-849c-7ff337ceb42d)
![Screenshot_20240111_005158_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/246d4301-9744-4036-90c0-7ed2f0f84de8)
![Screenshot_20240111_005050_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/44e21b04-55e4-47e7-b912-d1eeb3ed629e)
![Screenshot_20240111_005228_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/563d8e92-ace5-468e-8164-73aaf6bd77e5)
![Screenshot_20240111_005218_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/3b6baaed-c90e-492d-997d-0e28be85177d)
![Screenshot_20240111_005312_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/a11f07d0-9142-437b-a875-cd0bbcd66609)
![Screenshot_20240111_005320_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/5d189f0a-06ae-4455-9e3b-2bca58470921)




> 1. Show the entire error message
> 2. Are you talking about ImageView? Please add more details, all you've entered so far is ambiguous.

**Comment by hasrat-ali** [comment]
@TanTai97o Can you just copy entire message and send.

And pls give steps to reproduce

**Comment by TanTai97o** [comment]
> @TanTai97o Can you just copy entire message and send.
> 
> And pls give steps to reproduce 

java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
	at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:206)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27709)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27709)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27709)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27709)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27709)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:27709)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27709)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27709)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:27709)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1366)
	at android.view.View.measure(View.java:27709)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4711)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3301)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3607)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by hasrat-ali** [comment]
How you're getting those error.
Tell me what exactly you are doing?

**Comment by TanTai97o** [comment]
> How you're getting those error.
> Tell me what exactly you are doing?

That error occurs when I edit it, for example changing the scale, changing the height, width, or image changes, generally just trying to edit is Sketchware crashes

**Comment by adesonob** [comment]
ImageView or CardView?

**Comment by TanTai97o** [comment]
> ImageView or CardView?

@adesonob ImageView

**Comment by ZylaconeEpindigo** [comment]
Attempting to edit image of image view causes crash.  Image resources are available in project.  No properties in properties window decorated.  Dialog boxes in IDE not decorated.
![Screenshot_20240601-210306](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/171465801/842b7d23-9123-466f-be17-4de96198df7d)

**Comment by hasrat-ali** [comment]
There is now a fix for this. Click on the `Show source code` then copy your XML codes and open `Direct XML editor` and paste and save.
