### ISSUE TITLE
Error adding component event 

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1061]
**Describe the bug**

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1356)
	at a.a.a.br$Adapter$ViewHolder$EventViewHolder.lambda$new$0(br.java:277)
	at a.a.a.br$Adapter$ViewHolder$EventViewHolder.$r8$lambda$1-x2wvEUHQ3fVbNUkTfokVn8NR4(Unknown Source:0)
	at a.a.a.br$Adapter$ViewHolder$EventViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7881)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Device and Sketchware Pro-related info:
 - Device: SamSungA51
 - OS: Android13
 - Sketchware Pro version: Version v6.4.0-SNAPSHOT-be51bbb-minApi26

**Comment by JavkhlanK** [comment]
The only reason I asked you to use the template is to also get to know the steps to reproduce the crash. Why didn't you fill those sections out?

**Comment by TanTai97o** [comment]
> The only reason I asked you to use the template is to also get to know the steps to reproduce the crash. Why didn't you fill those sections out?

@JavkhlanK 
Sorry about that
Just click here,sketchware is crashes
![Screenshot_20240112_193008_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/a22c104f-393b-4b3e-ba11-0f1b62eb5108)
