### ISSUE TITLE
Sign Apk With Test Key bugs

### ISSUE THREAD

**Issue by Alotuna** [Sketchware-Pro/Sketchware-Pro#1073]
**Describe the bug**

When I clicked on sign apk with test key the sketchware was crashes

java.lang.ClassCastException: com.google.android.material.textfield.TextInputEditText cannot be cast to com.besome.sketch.lib.ui.EasyDeleteEditText
	at mod.hilal.saif.activities.tools.Tools.signApkFileDialog(Tools.java:273)
	at mod.hilal.saif.activities.tools.Tools.lambda$setupViews$6(Tools.java:255)
	at mod.hilal.saif.activities.tools.Tools.$r8$lambda$rDxThmcAlcTZd4aSHZmbXq-qTdE(Unknown Source:0)
	at mod.hilal.saif.activities.tools.Tools$$ExternalSyntheticLambda10.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6599)
	at android.view.View.performClickInternal(View.java:6576)
	at android.view.View.access$3100(View.java:780)
	at android.view.View$PerformClick.run(View.java:25899)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

v6.4.0-SNAPSHOT-5460da8-minApi26

**Comment by Win-one** [comment]
me too!Maybe it's because“EasyDeleteEditText”is too old!

**Comment by Alotuna** [comment]
> me too!Maybe it's because“EasyDeleteEditText”is too old!
I don't think it's too old, just an error in the code of the dialog box

**Comment by Win-one** [comment]
change"EasyDeleteEditText"to"TextInputEditTxt"!

**Comment by ilyassesalama** [comment]
I couldn't reproduce the mentioned issue. Are you sure you've tried the latest version provided by GitHub actions? if not, please download it [from here](https://nightly.link/Sketchware-Pro/Sketchware-Pro/workflows/android/material-redesign?status=completed).

**Comment by TanTai97o** [comment]
> I couldn't reproduce the mentioned issue. Are you sure you've tried the latest version provided by GitHub actions? if not, please download it [from here](https://nightly.link/Sketchware-Pro/Sketchware-Pro/workflows/android/material-redesign?status=completed).

Tried the new version but still error

**Comment by TanTai97o** [comment]
> I couldn't reproduce the mentioned issue. Are you sure you've tried the latest version provided by GitHub actions? if not, please download it [from here](https://nightly.link/Sketchware-Pro/Sketchware-Pro/workflows/android/material-redesign?status=completed).

I Tried the new version but still error

**Comment by hasrat-ali** [comment]
This issue is already fixed. Try newer build.
