### ISSUE TITLE
Sound Collection Manager bugs

### ISSUE THREAD

**Issue by Alotuna** [Sketchware-Pro/Sketchware-Pro#1074]
**Describe the bug**

When adding new sound to collection in the collection manager,sketchware was crashes

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sketchware.remod/com.besome.sketch.editor.manage.sound.AddSoundCollectionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2958)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
	at com.besome.sketch.editor.manage.sound.AddSoundCollectionActivity.onCreate(Unknown Source:132)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
	... 11 more
v6.4.0-SNAPSHOT-5460da8-minApi26

**Comment by ilyassesalama** [comment]
This should be fixed now. Thanks for the report.
