### ISSUE TITLE
Add font to collection in Collection Manager was bugs

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1076]
**Describe the bug**

When I click here, Sketchware crashes

![Screenshot_20240122_232500_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/6a1ffc30-ff17-43bf-85b0-050a2662972a)

Entire error message

java.lang.NoSuchMethodError: No static method a(Lcom/besome/sketch/editor/manage/font/AddFontCollectionActivity;)V in class Lcom/besome/sketch/editor/manage/font/AddFontCollectionActivity; or its super classes (declaration of 'com.besome.sketch.editor.manage.font.AddFontCollectionActivity' appears in /data/app/~~KPmcB3VYW_KQ9rrYrvyrXA==/com.sketchware.remod-8XAya_Wkt96fBTtuMs2h9w==/base.apk!classes18.dex)
	at a.a.a.Nt.onClick(Unknown Source:9)
	at android.view.View.performClick(View.java:7881)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Device and Sketchware Pro-related info:
 - Device: SamSungA51 
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-SNAPSHOT-7163c0d-minApi26

**Comment by Win-one** [comment]
id is error!

**Comment by ilyassesalama** [comment]
I couldn't reproduce the issue. Can you download the latest version produced by Github actions and try again?

**Comment by TanTai97o** [comment]
> I couldn't reproduce the issue. Can you download the latest version produced by Github actions and try again?

I tried the newer version and it was fixed !
