### ISSUE TITLE
You cannot create a new a block

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#1094]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5275)
	at android.view.ViewGroup.addView(ViewGroup.java:5104)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:657)
	at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
	at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
	at android.app.Dialog.show(Dialog.java:325)
	at mod.hilal.saif.lib.PCP.a(PCP.java:38)
	at a.a.a.Xx.onClick(Unknown Source:43)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by hasrat-ali** [comment]
Fixed with 2283354
