### ISSUE TITLE
After updating to AppCompat 1.6.1, Material Dialog Causes Crashes

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1139]
I'm not sure if this has anything to do with Sketchware or not but Material 3 dialog just doesn't work when I change app compat to 1.6.1 instead of the default version (1.4.0). Also, I added Activity 1.9.0. If App Compat stays at 1.4.0, a material 3 dialog shows up fine, but If I change it to 1.6.1 or 1.7.0, Material Dialogs all of a sudden don't work at all. I did a test with some other people and we realized that it does not crash on an Android 11 device but on my Android 14 device, it crashes. It must be due to some way that Sketchware compiles the project.

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/3fa8dc26-87ac-4224-9db4-edfbe5868978

![Screenshot_20240529_190344_ForU](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/312130b1-c893-4506-96a2-00121fc8d164)

**I was able to obtain this Crash Log:**
```
java.lang.NoSuchMethodError: No virtual method setOnBackInvokedDispatcher(Landroid/window/OnBackInvokedDispatcher;)V in class Landroidx/activity/OnBackPressedDispatcher; or its super classes (declaration of 'androidx.activity.OnBackPressedDispatcher' appears in /data/app/~~WZZgOIHYNzQ3iY3VsfKZ-w==/com.my.newproject2-wsm0t7Czm93PLL2H2LJb1Q==/base.apk!classes2.dex)
	at androidx.activity.ComponentDialog.onCreate(ComponentDialog.kt:72)
	at androidx.appcompat.app.AppCompatDialog.onCreate(AppCompatDialog.java:78)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:833)
	at android.app.Dialog.show(Dialog.java:453)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at com.my.newproject2.MainActivity$3.onClick(MainActivity.java:114)
	at android.view.View.performClick(View.java:8047)
	at android.widget.TextView.performClick(TextView.java:17792)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

Crash Log Tested Again:
```FATAL EXCEPTION: main
Process: com.my.newproject2, PID: 24347
java.lang.NoSuchMethodError: No virtual method setOnBackInvokedDispatcher(Landroid/window/OnBackInvokedDispatcher;)V in class Landroidx/activity/OnBackPressedDispatcher; or its super classes (declaration of 'androidx.activity.OnBackPressedDispatcher' appears in /data/app/~~GItHYR1Q1oVR2_uIka0n1w==/com.my.newproject2-lpatW9BIn_ijOkKVZzkmVw==/base.apk!classes2.dex)
	at androidx.activity.ComponentDialog.onCreate(ComponentDialog.kt:72)
	at androidx.appcompat.app.AppCompatDialog.onCreate(AppCompatDialog.java:81)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:277)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:833)
	at android.app.Dialog.show(Dialog.java:453)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1008)
	at com.my.newproject2.MainActivity$2.onCheckedChanged(MainActivity.java:79)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:235)
	at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1179)
	at androidx.appcompat.widget.SwitchCompat.toggle(SwitchCompat.java:1174)
	at android.widget.CompoundButton.performClick(CompoundButton.java:155)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)```

**Comment by HehehBoiii78** [comment]
For you, it's just a part of your app (M3 dialog) that doesn't work. I did the same thing, and my whole app freezes when I start it from my device's launcher.
