### ISSUE TITLE
Some duplicate entries are errors when creating app bundle (AAB)

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1180]
I am encountering an issue every time I attempt to export my project as an Android App Bundle (AAB). The export process consistently fails, generating an error related to a duplicate entry in the zip file, specifically `META-INF/com.android.tools/proguard/coroutines.pro`. 

This problem does not occur when exporting the project as an APK, which works without any issues. Additionally, the error message mentions ProGuard, even though ProGuard is not enabled in my project configuration.

The error details are as follows:

```
java.util.zip.ZipException: duplicate entry: root/META-INF/com.android.tools/proguard/coroutines.pro
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:234)
    at mod.jbk.build.compiler.bundle.AppBundleCompiler.createModuleMainArchive(AppBundleCompiler.java:211)
    at com.besome.sketch.export.ExportProjectActivity$BuildingAsyncTask.b(ExportProjectActivity.java:786)
    at a.a.a.MA.dlnBackground(MA.java:25)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
```

------

![Screenshot_20240630_104701_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/37d26a95-5c98-447a-b2b4-bb133695ba9b)

**Comment by subhash16** [comment]
0-SNAPSHOT- 10a7408 -minApi26

**Comment by hasrat-ali** [comment]
Can you try with [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/10007105414) build?

**Comment by guhg** [comment]
> Can you try with [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/10007105414) build?

Still happens. @
![Screenshot_20240721_094736_Sketchware Pro](https://github.com/user-attachments/assets/a77ddd85-35d3-4005-95ae-8af0437f3ed9)

**Comment by RoyTheReal** [comment]
@hasrat-ali @JavkhlanK It still happens. It's impossible to export any of my projects as an ABB. 
![Screenshot_20240909_110043_Sketchware Pro](https://github.com/user-attachments/assets/c42bd3c3-10d8-4727-ab75-0c781cc2d763)

**Comment by JavkhlanK** [comment]
The error messages aren't the same. You cannot say that the issue still occurs, no, you're having a different one.

Your latest issue is because you have two definitions of the androidx-core library. This is not a bug in Sketchware Pro. Fix your enabled Local libraries or excluded built-in libraries.

**Comment by RoyTheReal** [comment]
> The error messages aren't the same. You cannot say that the issue still occurs, no, you're having a different one.
> 
> Your latest issue is because you have two definitions of the androidx-core library. This is not a bug in Sketchware Pro. Fix your enabled Local libraries or excluded built-in libraries.

BUT I DON'T HAVE TWO DETENTIONS OF IT

**Comment by RoyTheReal** [comment]
> The error messages aren't the same. You cannot say that the issue still occurs, no, you're having a different one.
> 
> Your latest issue is because you have two definitions of the androidx-core library. This is not a bug in Sketchware Pro. Fix your enabled Local libraries or excluded built-in libraries.

@JavkhlanK I still do get the same error
![Screenshot_20240909_203057_Sketchware Pro](https://github.com/user-attachments/assets/4e11185f-42c3-4533-9873-55ca5eda03b8)

**Comment by RoyTheReal** [comment]
@JavkhlanK @hasrat-ali What's the issue?

**Comment by JavkhlanK** [comment]
2+ Local libraries have that mentioned file in their .jar file, you can edit those .jar files with a ZIP archive editor/extractor or a file manager. removing those files should be safe

**Comment by RoyTheReal** [comment]
> 2+ Local libraries have that mentioned file in their .jar file, you can edit those .jar files with a ZIP archive editor/extractor or a file manager. removing those files should be safe

How does this have to do with libraries? Did you not look at the screenshot? @JavkhlanK

**Comment by RoyTheReal** [comment]
@JavkhlanK I get this on projects even when I have no local libraries 
![Screenshot_20240910_120024_Sketchware Pro](https://github.com/user-attachments/assets/02208f27-9ce2-4233-bfc1-99e81dc3de20)

**Comment by JavkhlanK** [comment]
you don't need to ping me in every single comment btw

what exact used version? this exception should be caught and a dialog be shown appropriately

**Comment by RoyTheReal** [comment]
> as a workaround, try building that project normally, it should show a more detailed error message

When I build it normally, I don't get a compile error. Only with AAB export

**Comment by JavkhlanK** [comment]
are you 100 % sure? just try doing that. same project.

**Comment by RoyTheReal** [comment]
> are you 100 % sure? just try doing that. same project.

Okay I was wrong, that project was getting an error but once I fixed it it did start working but with projects with local libraries there's a ton of errors idk why because if I sign and build it as apk there are no errors, only when building the AAB

**Comment by RoyTheReal** [comment]
It's so annoying because now it's a completely different local librarie that's giving an error, I have all the local libraries I need for Material 1.12.0 to work. 
![Screenshot_20240910_121138_Sketchware Pro](https://github.com/user-attachments/assets/50f18bbb-07d9-476e-9991-3c3f97da6fe0)

**Comment by JavkhlanK** [comment]
> 2+ Local libraries have that mentioned file in their .jar file, you can edit those .jar files with a ZIP archive editor/extractor or a file manager. removing those files should be safe

@RoyTheReal this is the main issue

**Comment by RoyTheReal** [comment]
> > 2+ Local libraries have that mentioned file in their .jar file, you can edit those .jar files with a ZIP archive editor/extractor or a file manager. removing those files should be safe
> 
> @RoyTheReal this is the main issue

Why does AAB export get the error but signing apk is fine?

**Comment by JavkhlanK** [comment]
Creating a .aab file uses logic created by Sketchware Pro modders. Creating .apk files uses a library developed by Google.

By that logic, this is an error in that Sketchware Pro logic. I'll setup this for tracking that issue.

###### (this does not mean that I will work on this issue, I don't want to.)

**Comment by RoyTheReal** [comment]
> Creating a .aab file uses logic created by Sketchware Pro modders. Creating .apk files uses a library developed by Google.
> 
> By that logic, this is an error in that Sketchware Pro logic. I'll setup this for tracking that issue.
> 
> ###### (this does not mean that I will work on this issue, I don't want to.)

Okay thanks a lot

**Comment by Edward-NewGate-KOC** [comment]
Fixed in Commit: 8740b49e
