### ISSUE TITLE
Why compile fine but start the apk with ERROR when introducing  the  view code .xml and java class manually in Sketchware Pro?

### ISSUE THREAD

**Issue by oramirezd** [Sketchware-Pro/Sketchware-Pro#1213]
Which is the reason for the which to the treat of compile some projects in Skecthware Pro that used some library external in the view .xml using the library * .jar corresponding selected in the same Sketchware when is introduces manually the code without add the widget in the "View of Design" of the application? .In this case tried recreate the package "softpro.bot" where you can dowload the file *.swb in https://t.me/hichem_soft_sketchware_chat/1/81520 where its code source original you can download from https://github.com/naseemali925/Linkify used the library "android.support. *" but as Sketchware used "androidx" the I change the class java and the view .xml manually in "androidx" using the files * .jar corresponding where then of compile correctly but give error  that can not inflate in @ layout / activity_main.xml binary xml file line # 16: "com.beardedhen.androidbootstrap.bootstrapedittext" and this is all the lines of command that do reference to "com.beardedhen.androidbootstrap *" in the project taking correctly selected this library and other * .jar in Sketchware (other internal library that can not inflate for if single is: "de.hdodenhof.circleimageview.circleimageview or com.google.android.material.navigation.NavigationView"). Is necessary that the developers of Sketchware have in account find the method in the which is can compile projects correctly introducing or writing manually the view .xml and the class .java taking the library * jar selected correctly without need of add the widget in the "View of Design" of Sketchware because other IDE   not use "View of Design", but all is introducing the data of form manual as ApkBuilder(com.gmail.heagoo.apkbuilder), AIDE-IDE(com.aide.pro) for android, compile well, so, I hope that find the error and the can solve so have that use old methods of compilation for fix. 
I sow the vídeo https://youtu.be/ms7_AMxq1n4?si=cw1ajl7Uphfo3MjU where someone to say can help me to fix this problems but I am think about Sketchware not need an external methot for compile any project or library code intoducing manually or not becouse other IDE work with this external methot.

**Comment by oramirezd** [comment]
This is the crash error:


************* Crash Head ****************
Time Of Crash      : 2024_07_23-18_53_38
Device Manufacturer: motorola
Device Model       : Moto G Play
Android Version    : 7.1.1
Android SDK        : 25
App VersionName    : 1.0
App VersionCode    : 1
************* Crash Head ****************

java.lang.RuntimeException: Unable to start activity ComponentInfo{softpro.bot/softpro.bot.MainActivity}: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class com.beardedhen.androidbootstrap.BootstrapEditText
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class com.beardedhen.androidbootstrap.BootstrapEditText
Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class com.beardedhen.androidbootstrap.BootstrapEditText
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.beardedhen.androidbootstrap.BootstrapEditText" on path: DexPathList[[zip file "/data/app/softpro.bot-1/base.apk"],nativeLibraryDirectories=[/data/app/softpro.bot-1/lib/arm, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:609)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at softpro.bot.MainActivity.onCreate(MainActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:6687)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by JavkhlanK** [comment]
Please read error messages carefully, don't just have a quick glance or ignore them at all:
> java.lang.ClassNotFoundException: Didn't find class "com.beardedhen.androidbootstrap.BootstrapEditText"

Anyway this isn't a general-purpose Sketchware project help forum. This is only for Sketchware Pro bugs, features, etc.

**Comment by oramirezd** [comment]
Mabee this error occurs becouse this library *.jar its compiled with the library "android.support.*"  and Sketchware Pro use the library "android.*".

**Comment by JavkhlanK** [comment]
No, otherwise it'd also have this in the stack trace: `Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.…"`
