### ISSUE TITLE
When you save your project is show this error....

### ISSUE THREAD

**Issue by Mersi-LLC** [Sketchware-Pro/Sketchware-Pro#1259]
Sketchware Pro v6.4.0-SNAPSHOT-8867ab7-minApi26 (150)
base.apk size: 136 MB (136051340 B)
Locale: en_US
SDK version: 30
Brand: ZTE
Manufacturer: ZTE
Model: ZTE A7030

```
java.lang.ArrayIndexOutOfBoundsException: length=7; index=-4
	at com.google.android.material.loadingindicator.LoadingIndicatorDrawingDelegate.drawIndicator(LoadingIndicatorDrawingDelegate.java:122)
	at com.google.android.material.loadingindicator.LoadingIndicatorDrawable.draw(LoadingIndicatorDrawable.java:109)
	at com.google.android.material.loadingindicator.LoadingIndicator.onDraw(LoadingIndicator.java:119)
	at android.view.View.draw(View.java:22486)
	at android.view.View.updateDisplayListIfDirty(View.java:21342)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4581)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4554)
	at android.view.View.updateDisplayListIfDirty(View.java:21302)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4581)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4554)
	at android.view.View.updateDisplayListIfDirty(View.java:21302)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4581)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4554)
	at android.view.View.updateDisplayListIfDirty(View.java:21302)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4581)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4554)
	at android.view.View.updateDisplayListIfDirty(View.java:21302)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4225)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3952)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3213)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2024)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8319)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1048)
	at android.view.Choreographer.doCallbacks(Choreographer.java:858)
	at android.view.Choreographer.doFrame(Choreographer.java:793)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1033)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8373)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by ilyassesalama** [comment]
This issue should be fixed with commit [18e6ea2](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/18e6ea25a75b8ad7987cb21416ea8e648f3775f8).
