### ISSUE TITLE
crash by press this button

### ISSUE THREAD

**Issue by nalcwap** [Sketchware-Pro/Sketchware-Pro#1272]
**Describe the bug**
when i press this button in my tablet with android 5.02 minsdk21 the sketchware crashes
**To Reproduce**
1. press this button from image sketchware will crash with this error from log
...

**Expected behavior**
open that menu
**Screenshots**

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 10]
 - OS: [e.g. Android 13]
last sketchware crashes i tried old version and not crashes 

**Additional context**

**Comment by nalcwap** [comment]
![Screenshot_2024-10-04-10-00-08](https://github.com/user-attachments/assets/7a189d96-3455-48e8-a10d-2bf7c3d5805d)
![Screenshot_2024-10-04-10-00-08_LI](https://github.com/user-attachments/assets/ee7bd423-3d51-4112-b61c-53d8f5c2685b)


error of crash 
Sketchware Pro v6.4.0-SNAPSHOT-7a902d2-minApi21 (150)
base.apk size: 96,26MB (100938048 B)
Locale: pt_PT
SDK version: 21
Brand: lge
Manufacturer: LGE
Model: LG-V480

```
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Landroid/view/View;III)V in class Landroid/widget/PopupMenu; or its super classes (declaration of 'android.widget.PopupMenu' appears in /system/framework/framework.jar)
	at com.besome.sketch.design.DesignActivity.onClick(DesignActivity.java:325)
	at android.view.View.performClick(View.java:4764)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View$PerformClick.run(View.java:19844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5351)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

```
