### ISSUE TITLE
Building a debug APK causes resource leak

### ISSUE THREAD

**Issue by ilyassesalama** [Sketchware-Pro/Sketchware-Pro#1283]
**Describe the bug**
When building a debug APK, the APKSigner class causes a resource leak in function `signWithTestkey()`.

**To Reproduce**
1. Compile the project in `DesignActivity`.

**Expected behavior**
The resource must be closed after being used.

Device and Sketchware Pro-related info:
 - Device: Samsung S24 Ultra
 - OS: Android 14
 - Sketchware Pro version: v6.4.0-SNAPSHOT-97f2bb121-minApi26

Additional context:
```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. (Ask Gemini)
	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1994)
	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
	at java.util.zip.Deflater.finalize(Deflater.java:575)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
	at java.lang.Daemons$Daemon.run(Daemons.java:145)
	at java.lang.Thread.run(Thread.java:1012)
	Caused by: java.lang.Throwable: Explicit termination method 'end' not called
	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
	at dalvik.system.CloseGuard.open(CloseGuard.java:257)
	at java.util.zip.Deflater.<init>(Deflater.java:189)
	at com.android.apksig.internal.zip.ZipUtils.deflate(ZipUtils.java:349)
	at com.android.apksig.ApkSigner.outputDataToOutputApk(ApkSigner.java:643)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:549)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:214)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:381)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
	at mod.alucard.tn.apksigner.ApkSigner.signWithTestKey(ApkSigner.java:57)
	at mod.jbk.util.TestkeySignBridge.signWithTestkey(TestkeySignBridge.java:11)
	at a.a.a.ProjectBuilder.signDebugApk(ProjectBuilder.java:791)
	at com.besome.sketch.design.DesignActivity$BuildTask.doInBackground(DesignActivity.java:1032)
	at com.besome.sketch.design.DesignActivity$BuildTask.$r8$lambda$0AmVsWQJ9oulgeP8eMAUbl0tGkA(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$BuildTask$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)

**Comment by PranavPurwar** [comment]
internal apksigner behaviour, needs to be fixed upstream
