### ISSUE TITLE
Crashing when downloading dependency

### ISSUE THREAD

**Issue by redowan178** [Sketchware-Pro/Sketchware-Pro#1298]
Sketchware Pro v6.4.0-SNAPSHOT-7d0d4b8-minApi26 (150)
base.apk size: 136 MB (136094199 B)
Locale: en_GB
SDK version: 29
Brand: POCO
Manufacturer: Xiaomi
Model: M2006C3MI

```
java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at dev.aldi.sayuti.editor.manage.LibraryDownloaderDialogFragment$1.lambda$onTaskCompleted$5(LibraryDownloaderDialogFragment.java:215)
	at dev.aldi.sayuti.editor.manage.LibraryDownloaderDialogFragment$1.$r8$lambda$VIL05S7hgkArpPzmo3LS73yxrcE(Unknown Source:0)
	at dev.aldi.sayuti.editor.manage.LibraryDownloaderDialogFragment$1$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

```

**Comment by hasrat-ali** [comment]
Fixed with #1364
