### ISSUE TITLE
When i restore, i got this error 


### ISSUE THREAD

**Issue by laymintu** [Sketchware-Pro/Sketchware-Pro#1384]
https://github.com/user-attachments/assets/6fcd1209-cf0f-422d-b280-244f3f7cf995

Sketchware Pro v6.4.0-SNAPSHOT-8a904a0-minApi26 (150)
base.apk size: 138 MB (138199988 B)
Locale: en_US
SDK version: 34
Brand: Redmi
Manufacturer: Xiaomi
Model: 2312DRA50G

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setId(int)' on a null object reference
	at com.besome.sketch.editor.view.ViewPane.createItemView(ViewPane.java:292)
	at com.besome.sketch.editor.view.ViewEditor.createAndAddView(ViewEditor.java:683)
	at com.besome.sketch.editor.view.ViewEditor.a(ViewEditor.java:960)
	at a.a.a.ViewEditorFragment.a(ViewEditorFragment.java:165)
	at a.a.a.ViewEditorFragment.b(ViewEditorFragment.java:193)
	at a.a.a.ViewEditorFragment.i(ViewEditorFragment.java:351)
	at a.a.a.ViewEditorFragment.a(ViewEditorFragment.java:132)
	at com.besome.sketch.design.DesignActivity.lambda$onCreate$12(DesignActivity.java:433)
	at com.besome.sketch.design.DesignActivity.$r8$lambda$SaLclm4ltx6dU-104bDY8a8SIbc(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda8.a(D8$$SyntheticClass:0)
	at com.besome.sketch.editor.view.ProjectFileSelector.syncState(ProjectFileSelector.java:207)
	at com.besome.sketch.design.DesignActivity.lambda$askIfToRestoreOldUnsavedProjectData$15(DesignActivity.java:664)
	at com.besome.sketch.design.DesignActivity.$r8$lambda$Y7dz1zQErDDP-0yXM0_uRjKRpQg(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda17.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7798)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:7775)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31225)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

**Comment by Mustiy0** [comment]
Can u send your project?

**Comment by trindadedev13** [comment]
Maybe this project was created by some other sketchware mod, like SkFu

**Comment by laymintu** [comment]
> Maybe this project was created by some other sketchware mod, like Sk

No official sk pro

**Comment by laymintu** [comment]
> Can u send your project?
> 
I can't send my 3 year project here 
Sorry about that

**Comment by trindadedev13** [comment]
try latest and tell me
