### ISSUE TITLE
Error in Built-in Library 

### ISSUE THREAD

**Issue by soiadmahedi** [Sketchware-Pro/Sketchware-Pro#1408]
**Describe the bug**
Please give us a clear and concise description of what the bug is.

Error:

java.lang.IllegalArgumentException: Unknown built-in library 'error_prone_annotations-2.27.0'!
	at a.a.a.BuiltInLibraryUtils.hasResources(BuiltInLibraryUtils.java:47)
	at a.a.a.Jp.<init>(Jp.java:18)
	at a.a.a.BuiltInLibraryManager.addLibrary(BuiltInLibraryManager.java:40)
	at a.a.a.BuiltInLibraryManager.addDependencies(BuiltInLibraryManager.java:54)
	at a.a.a.BuiltInLibraryManager.addLibrary(BuiltInLibraryManager.java:41)
	at a.a.a.ProjectBuilder.buildBuiltInLibraryInformation(ProjectBuilder.java:765)
	at com.besome.sketch.design.DesignActivity$BuildTask.doInBackground(DesignActivity.java:971)
	at com.besome.sketch.design.DesignActivity$BuildTask.$r8$lambda$0AmVsWQJ9oulgeP8eMAUbl0tGkA(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$BuildTask$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

Device and Sketchware Pro-related info:
 - Device: [e.g. Realme C55]
 - OS: [e.g. Android 14]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-1ea8b69-minApi26]

**Comment by araafroyall** [comment]
seems you are using nightly version. just update app to latest or last released version to fix .

**Comment by hasrat-ali** [comment]
Fixed with ae4c836b003d4bc8b7cb949207bc3efed260871e
