### ISSUE TITLE
Unable to show source code

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1424]
Device: Redmi Turbo 3.
OS: HyperOS 1.0.16.0.
Android version: 14.
Sketchware version: v6.4.0-SNAPSHOT-e907df5-minApi26
Error:

Sketchware Pro v6.4.0-SNAPSHOT-e907df5-minApi26 (150)
base.apk size: 157 MB (156690737 B)
Locale: en_US
SDK version: 34
Brand: Redmi
Manufacturer: Xiaomi
Model: 24069RA21C

```
java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
	at java.lang.String.substring(String.java:2517)
	at a.a.a.Lx.a(Lx.java:254)
	at a.a.a.Fx.a(Fx.java:585)
	at a.a.a.Fx.a(Fx.java:1333)
	at a.a.a.Fx.a(Fx.java:1230)
	at a.a.a.Fx.a(Fx.java:1333)
	at mod.hey.studios.editor.manage.block.code.ExtraBlockCode.getCodeExtraBlock(ExtraBlockCode.java:93)
	at a.a.a.Fx.a(Fx.java:76)
	at a.a.a.Fx.a(Fx.java:48)
	at a.a.a.Jx.addMoreBlockCodes(Jx.java:880)
	at a.a.a.Jx.generateCode(Jx.java:180)
	at a.a.a.yq.getFileSrc(yq.java:919)
	at com.besome.sketch.design.DesignActivity.lambda$showCurrentActivitySrcCode$19(DesignActivity.java:729)
	at com.besome.sketch.design.DesignActivity.$r8$lambda$-lX0tzQd8z1GWEbyAitk60BkvNs(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by HanzoDev1375** [comment]
@hasrat-ali  زمانی که appcompat را فعال میکنم فایل apk خطای تجزیه میدهد خودت چک کن ببین میتونی درستش کنی؟

**Comment by AnBui2004** [comment]
> @hasrat-ali زمانی که appcompat را فعال میکنم فایل apk خطای تجزیه میدهد خودت چک کن ببین میتونی درستش کنی؟

If you are using the Nightly version, I recommend that you regularly zip the .sketchware folder to safely backup all your projects. Sketchware Pro's backup feature is inefficient and can cause problems that ruin your project. Currently, if you want to use the Nightly version, use v6.4.0-SNAPSHOT-af2c490-minApi26 as it has the least issues.

**Comment by AnBui2004** [comment]
I found out the cause of the problem, it was because this block was empty. In previous versions of Sketchware it would automatically ignore it if it was empty but in the latest Nightly version it doesn't.

![InShot_20241130_111011397](https://github.com/user-attachments/assets/f903ae5e-e1f3-4e1f-a669-d717d99033dd)

**Comment by HanzoDev1375** [comment]
@hasrat-ali پیام منو به عنوان اسپم ثبت میکنی؟

**Comment by HanzoDev1375** [comment]
کونت میخاره اگر کونت میخاره بگو مخزنتو مسدود کنم
