### ISSUE TITLE
🔥 Sketchware crashes on changing themes (System)

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1435]
**What is the bug?**
1. Open any sketchware project.
2. Change device theme (dark/light)
3. Sketchware crashes

**For better understanding, here is a video**
https://github.com/user-attachments/assets/95d75df0-90b2-425b-8207-199d7ae44d0e

**Sketchware version**
v6.4.0-SNAPSHOT-4de627c-minApi26

**CRASH LOG**
Sketchware Pro v6.4.0-SNAPSHOT-4de627c-minApi26 (150)
base.apk size: 157 MB (156996871 B)
Locale: en_GB
SDK version: 34
Brand: samsung
Manufacturer: samsung
Model: SM-A346B

```
java.lang.RuntimeException: Unable to resume activity {official.sketchware.pro.debug/com.besome.sketch.design.DesignActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=122418665, result=-1, data=null} to activity {official.sketchware.pro.debug/com.besome.sketch.design.DesignActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void a.a.a.ViewEditorFragment.i()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5427)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=122418665, result=-1, data=null} to activity {official.sketchware.pro.debug/com.besome.sketch.design.DesignActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void a.a.a.ViewEditorFragment.i()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6063)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5396)
	... 13 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void a.a.a.ViewEditorFragment.i()' on a null object reference
	at com.besome.sketch.design.DesignActivity.lambda$new$5(DesignActivity.java:182)
	at com.besome.sketch.design.DesignActivity.$r8$lambda$VAQ_tvZyvBIfLKMCZ6QkiDIkFsI(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda6.onActivityResult(D8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
	at android.app.Activity.dispatchActivityResult(Activity.java:9362)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6056)
	... 14 more

```

**Comment by elfilibusterismo** [comment]
Fixed in https://github.com/Sketchware-Pro/Sketchware-Pro/commit/3159565ed8a5f136e51613cc5869a91e2cffd526
