### ISSUE TITLE
Sketchware is being killed!

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1458]
AppCompat was destroyed due to library conflicts! This is happening on the latest Nightly version.

FATAL EXCEPTION: main
Process: com.my.app, PID: 3093
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
	at android.app.ActivityThread.installProvider(ActivityThread.java:8360)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7859)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7511)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2382)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8790)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: androidx.startup.StartupException: java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:239)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:207)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2636)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2602)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8355)
	... 11 more
Caused by: java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
	at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
	at androidx.emoji2.text.EmojiCompatInitializer.delayUntilFirstResume(EmojiCompatInitializer.java:101)
	at androidx.emoji2.text.EmojiCompatInitializer.create(EmojiCompatInitializer.java:86)
	at androidx.emoji2.text.EmojiCompatInitializer.create(EmojiCompatInitializer.java:71)
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
	... 17 more

**Comment by StudioAsInc** [comment]
Use the latest version... Now I have no problem.

**Comment by hasrat-ali** [comment]
You are using older build. Try [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/12097874141).
