### ISSUE TITLE
Direct code editor bugs

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1466]
This error occurs when applying 
``` android:src="@mipmap/ic_launcher" ```

Sketchware Pro v6.4.0-SNAPSHOT-deb32bd-minApi26 (150)
base.apk size: 125 MB (125349061 B)
SDK version: 33
Brand: samsung
Manufacturer: samsung
Model: SM-A515F

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.besome.sketch.editor.view.ViewPane.updateItemView(ViewPane.java:441)
	at com.besome.sketch.editor.view.ViewPane.createItemView(ViewPane.java:296)
	at com.besome.sketch.editor.view.ViewEditor.createAndAddView(ViewEditor.java:685)
	at com.besome.sketch.editor.view.ViewEditor.a(ViewEditor.java:969)
	at a.a.a.ViewEditorFragment.a(ViewEditorFragment.java:165)
	at a.a.a.ViewEditorFragment.b(ViewEditorFragment.java:193)
	at a.a.a.ViewEditorFragment.i(ViewEditorFragment.java:355)
	at com.besome.sketch.design.DesignActivity.lambda$new$6(DesignActivity.java:189)
	at com.besome.sketch.design.DesignActivity.$r8$lambda$cwHrNiG1_wDgAv0oqlBbB1AMSxw(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda10.onActivityResult(D8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry.register$lambda$1(ActivityResultRegistry.kt:113)
	at androidx.activity.result.ActivityResultRegistry.$r8$lambda$TWvtyPFk-iHdx0R-btWVLevVLT0(Unknown Source:0)
	at androidx.activity.result.ActivityResultRegistry$$ExternalSyntheticLambda0.onStateChanged(D8$$SyntheticClass:0)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.kt:121)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1465)
	at android.app.Activity.performStart(Activity.java:8653)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Comment by elfilibusterismo** [comment]
Fixed in https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/12126868300

Unfortunately, the View Editor does not currently support mipmap resources. If you use @mipmap/something, it will likely be added to the inject property instead.
