### ISSUE TITLE
⚠️ Crashes when change layout pedding or other details

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1487]
### What is the bug?
The app crashes (not on all custom views) when I change app pedding or height/width

**Here is an example of the bug**
https://github.com/user-attachments/assets/f53a0d54-f909-43aa-95a0-31c826903288

**On which version of Sketchware pro?**
SNAPSHOT-100c7dc-minApi26

⚠️ **Crashlog of Sketchware**
Sketchware Pro v6.4.0-SNAPSHOT-100c7dc-minApi26 (150)
base.apk size: 125 MB (125427553 B)
Locale: en_GB
SDK version: 34
Brand: samsung
Manufacturer: samsung
Model: SM-A346B

```
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
	at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:211)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28571)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28571)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28571)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:28571)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28571)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:28571)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1036)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5203)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3973)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

**Comment by elfilibusterismo** [comment]
Fixed in https://github.com/Sketchware-Pro/Sketchware-Pro/commit/a8f9e6ac6c3dfde8ac4944baa387e728ba1b63c8
