### ISSUE TITLE
Sketchware pro application, Component Manager option problem, An error occurred 

### ISSUE THREAD

**Issue by mariyaakter123** [Sketchware-Pro/Sketchware-Pro#1505]
![Screenshot_2024_1217_155542](https://github.com/user-attachments/assets/6c0431ad-04a8-4a5e-a2cb-3c1dc646911e)

![Screenshot_20241217_155505](https://github.com/user-attachments/assets/359a7f0f-2977-4d59-8ce3-c914ec668575)
Sketchware pro application,Component Manager option problem, An error occurred!

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at mod.hilal.saif.activities.tools.ComponentsMaker$ListAdapter.getView(ComponentsMaker.java:216)
	at android.widget.AbsListView.obtainView(AbsListView.java:2647)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
	at android.widget.ListView.onMeasure(ListView.java:1323)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at com.android.internal.policy.DecorView.measureChildWithMargins(DecorView.java:3496)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:975)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4074)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2724)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3075)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2436)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9464)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1228)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1012)
	at android.view.Choreographer.doFrame(Choreographer.java:922)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

Please help me sir/mam🙏

**Comment by akash-malik-18** [comment]
#help
Error Cause:
The error is caused at ComponentsMaker.java:216 when the getView method is
trying to invoke toString() on an object that is null.

Code Flow:
The issue arises while populating the list in the Component Manager. The
code at ListAdapter.getView is likely trying to fetch a component's name or
details but encounters a null value.

---

Steps to Fix

1. Check the Null Value:
Open ComponentsMaker.java and navigate to line 216 in the getView method.
Add a null check before calling toString():

if (object != null) {
    textView.setText(object.toString());
} else {
    textView.setText("Unknown Component");
}

**Comment by akash-malik-18** [comment]
Error Cause:
The error is caused at ComponentsMaker.java:216 when the getView method is trying to invoke toString() on an object that is null.

Code Flow:
The issue arises while populating the list in the Component Manager. The code at ListAdapter.getView is likely trying to fetch a component's name or details but encounters a null value.



---

Steps to Fix

1. Check the Null Value:
Open ComponentsMaker.java and navigate to line 216 in the getView method. Add a null check before calling toString():

if (object != null) {
    textView.setText(object.toString());
} else {
    textView.setText("Unknown Component");
}

**Comment by PranavPurwar** [comment]
We don't want AI solutions. Just report the bug and additional useful information, not AI output.

**Comment by PranavPurwar** [comment]
Also its fixed in nightly builds.

**Comment by mariyaakter123** [comment]
I understand what you are saying. Now I need that project to solve that problem but I don't have that project. I took the json file of that project from him. Maybe there was a problem in his project, so there was a problem in the json file given to me. Now I don't remember who gave me that json file, so I can't do anything. That project swb to solve this problem, If you can, please solve the code given below. The problem is caused by the Json file given below. If you can, please solve the problem of this code.

Problem: An error occurred!
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at mod.hilal.saif.activities.tools.ComponentsMaker$ListAdapter.getView(ComponentsMaker.java:216)
	at android.widget.AbsListView.obtainView(AbsListView.java:2647)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
	at android.widget.ListView.onMeasure(ListView.java:1323)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
	at com.android.internal.policy.DecorView.measureChildWithMargins(DecorView.java:3496)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:975)
	at android.view.View.measure(View.java:26154)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4074)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2724)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3075)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2436)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9464)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1228)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1012)
	at android.view.Choreographer.doFrame(Choreographer.java:922)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

-----------------------------------------------------------------

JSON File

12-15 21:30:23.643  1297  1783 D _V_VivoWatchdogImpl: /dev/block/dm-5         3026628  3017472      9156 100% /
12-16 18:08:21.029 17472 17472 E AndroidRuntime: FATAL EXCEPTION: main
12-16 18:08:21.029 17472 17472 E AndroidRuntime: Process: com.sketchware.remod, PID: 17472
12-16 18:08:21.029 17472 17472 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at mod.hilal.saif.activities.tools.ComponentsMaker$ListAdapter.getView(ComponentsMaker.java:216)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2647)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1323)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.View.measure(View.java:26154)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.View.measure(View.java:26154)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.View.measure(View.java:26154)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.View.measure(View.java:26154)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.View.measure(View.java:26154)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7128)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at com.android.internal.policy.DecorView.measureChildWithMargins(DecorView.java:3496)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:975)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.View.measure(View.java:26154)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4074)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2724)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3075)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2436)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9464)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1228)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1012)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:922)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:334)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8517)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
12-16 18:08:21.029 17472 17472 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
