### ISSUE TITLE
Crashing while exporting (.aab) + Minor UI bugs report

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1510]
**What is the problem?**
Which exporting **.aab** from Sketchware pro. It throws an error at the end.

**What is that error?**
java.util.zip.ZipException:
duplicate entry: root/META-INF/
androidx.interpolator_interpolator.version
at
java.util.zip.ZipOutputStream.putNextEntr
y(ZipOutputStream.java:246)
at
mod.jbk.build.compiler.bundle.AppBundleC
ompiler. createModuleMainArchive(AppBun
dleCompiler.java:211)
at
com.besome.sketch.export.ExportProjectA
ctivity$BuildingAsyncTask.b(ExportProject
Activity.java:621)
at a.a.a.MA.dolnBackground(MA.java:25)
at a.a.a.MA.dolnBackground(MA.java:10)
at
android.os.AsyncTask$3.call(AsyncTask.jav
a:394)
at
java.util.concurrent.FutureTask.run(FutureT
ask.java:264)
at
android.os.AsyncTask$SerialExecutor$1.ru
n(AsyncTask.java:305)
at
java.util.concurrent.ThreadPoolExecutor.ru
nWorker(ThreadPoolExecutor.java:1145)
at
java.util.concurrent.ThreadPoolExecutor$W
orker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)

**Screenshots**
![Screenshot_20241219_113035_Sketchware Pro.jpg](https://github.com/user-attachments/assets/d61d7784-40eb-4450-acc1-ba705c789579)

**Take note:** The project doesn't contain any error, I rechecked it by **compiling** **.apk** | And it works without error.

**Informations that might help you!**
**Device:** Based on Android 14
**RAM:** 6 GB
**SW ver:** [https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/12403134497](**Debug 7.0.0**)

**Additional bugs**
Horizontal scroll is not working while importing saved more block
![IMG_20241219_114602_360.jpg](https://github.com/user-attachments/assets/2ff534e0-e83d-4026-8f14-461e4ae18dd3)

Progress Dialogues progress stopped animation while Sketchware was in the background.
https://github.com/user-attachments/assets/19ec39dc-8b73-480f-9274-935bb03619e1

**Comment by Edward-NewGate-KOC** [comment]
Fixed in Commit: 8740b49e, 5cd486dd
