### ISSUE TITLE
NullPointerException in Direct XML Editor

### ISSUE THREAD

**Issue by redowan178** [Sketchware-Pro/Sketchware-Pro#1530]
**Description:**  
When I try to access the Direct XML Editor in Sketchware, the app crashes and displays a NullPointerException. This issue occurs consistently.  

**Steps to Reproduce:**  
1. Open Sketchware.  
2. Navigate to any project.  
3. Attempt to open the Direct XML Editor.  

**Expected Behavior:**  
The Direct XML Editor should open and allow editing without crashing.  

**Actual Behavior:**  
The app crashes with the following error:  

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.besome.sketch.beans.ProjectFileBean.getXmlName()' on a null object reference
	at a.a.a.Ox.writeRootLayout(Ox.java:88)
	at a.a.a.Ox.a(Ox.java:256)
	at com.besome.sketch.design.DesignActivity.lambda$toViewCodeEditor$23(DesignActivity.java:903)
	at com.besome.sketch.design.DesignActivity.$r8$lambda$NSAdb71fMbcJNjK7G3DKM82W3yE(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$$ExternalSyntheticLambda17.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:919)
```

**Environment:**  
- **Device:** Poco C3  
- **Android Version:** 10  
- **Sketchware Version:** v7.0.0-SNAPSHOT-8726823-minApi26  

**Additional Notes:**  
- This issue might be related to `ProjectFileBean` being null.  
- Please let me know if further information or logs are needed.  

---

**Comment by elfilibusterismo** [comment]
This has been fixed already
