### ISSUE TITLE
Compilation Error in Sketchware Pro on Android 14 (Version V6.4.0-rc-minApi26)

### ISSUE THREAD

**Issue by JeamDeveloper** [Sketchware-Pro/Sketchware-Pro#1553]
Bug Description
When compiling any project in Sketchware Pro, a strange error occurs. This happens even when creating a project from scratch. The error is persistent and seems to be related to an internal application issue.

Steps to Reproduce:

1. Open Sketchware Pro on a Samsung S24 Ultra device running Android 14.

2. Create a new project from scratch or open an existing one.

3. Attempt to compile the project.

Expected Behavior:
The project should compile without errors and produce the expected output.

Screenshots:
![Screenshot_Sketchware Pro](https://github.com/user-attachments/assets/cf87ce91-dd1c-4843-9ff5-ce72dbe0defa)

Device and Sketchware Pro Info:

Device: Samsung S24 Ultra.

OS: Android 14.

Sketchware Pro Version: V6.4.0-rc-minApi26.

Error Text:

(444$()8�8�@�@�@�l�l��|�� �� 8�8� 5!5!���|�� ��  R�td�|�� �� 8�@�P�tdp�p�p�||Q�td���88p��� � �AndroidGNU+2o��,�$��Z���t�t������������������P�����T��������
������t����h����T������������������������2�X������������
�������2�<���$�����2�����������L���������n ���� ����� ���� ����!���$���8$���&����'����(���,��
���p�\����������?������������L�L�����l�H�\����������<�H�@�<�D�|����������������6�������h��������
�������������������<�����D���
����������������8����d���������T	�����	�����
�Td����Xe�����e��
���.�����
�������������������������
����������4���������"�����:����'

Additional Context:
I’ve tried uninstalling and reinstalling the app, but the problem persists. It also happens with different project configurations, indicating that it’s not related to a specific project.

**Comment by PranavPurwar** [comment]
You can download [nightly versions](https://nightly.link/Sketchware-Pro/Sketchware-Pro/workflows/android/main) that include a fix for it.

**Comment by JeamDeveloper** [comment]
> You can download [nightly versions](https://nightly.link/Sketchware-Pro/Sketchware-Pro/workflows/android/main) that include a fix for it.

My phone says it contains malware, virus total give me the same advise of malware

**Comment by PranavPurwar** [comment]
Those are false positives that show up because the app was signed with debug signature key

**Comment by lanz132** [comment]
Sir what version u use?

**Comment by ffrobin2023-eng** [comment]
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/606/app/src/main/java/com/shuvo/fungames/MainActivity.java (at line 152)
	Sheet.setCancelable(false);
	^^^^^
Sheet cannot be resolved

**Comment by farhanibrahim2024-source** [comment]
a.a.a.By: Failed to add /storage/emulated/0/.sketchware/libs/local_libs/EveryThingUtils_V_v1.5/classes.jar
	at a.a.a.Dp.buildApk(Dp.java:622)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1073)
	at a.a.a.MA.a(dex-id-9d328ca9d27c29940cc73c21188268863fcedf1e:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1572)
