### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by redowan178** [Sketchware-Pro/Sketchware-Pro#1554]
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:221)
	at mod.pranav.viewbinding.ViewBindingBuilder.generateBindingForLayout(ViewBindingBuilder.kt:20)
	at mod.pranav.viewbinding.ViewBindingBuilder.generateBindings(ViewBindingBuilder.kt:13)
	at a.a.a.ProjectBuilder.generateViewBinding(ProjectBuilder.java:176)
	at com.besome.sketch.design.DesignActivity$BuildTask.doInBackground(DesignActivity.java:1190)
	at com.besome.sketch.design.DesignActivity$BuildTask.$r8$lambda$0AmVsWQJ9oulgeP8eMAUbl0tGkA(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$BuildTask$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by redowan178** [comment]
Fixed
