### ISSUE TITLE
Component manager crash bug

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1555]
Sketchware Pro v7.0.0-SNAPSHOT-219ceff-minApi26 (150)
base.apk size: 126 MB (125906911 B)
Locale: en_US
SDK version: 35
Brand: samsung
Manufacturer: samsung
Model: SM-X700

```
android.view.InflateException: Binary XML file line #93 in pro.sketchwaree:layout/manage_custom_component_list_item: Binary XML file line #93 in pro.sketchwaree:layout/manage_custom_component_list_item: Error inflating class pro.sketchware.activities.editor.component.CollapsibleCustomComponentLayout
Caused by: android.view.InflateException: Binary XML file line #93 in pro.sketchwaree:layout/manage_custom_component_list_item: Error inflating class pro.sketchware.activities.editor.component.CollapsibleCustomComponentLayout
Caused by: java.lang.ClassNotFoundException: pro.sketchware.activities.editor.component.CollapsibleCustomComponentLayout
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java:843)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:700)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at pro.sketchwaree.activities.editor.component.ManageCustomComponentActivity$ComponentsAdapter.onCreateViewHolder(ManageCustomComponentActivity.java:250)
	at pro.sketchwaree.activities.editor.component.ManageCustomComponentActivity$ComponentsAdapter.onCreateViewHolder(ManageCustomComponentActivity.java:235)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7788)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:145)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2360)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1102)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5349)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4589)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3345)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1690)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
	at android.view.Choreographer.doFrame(Choreographer.java:1080)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.ClassNotFoundException: pro.sketchware.activities.editor.component.CollapsibleCustomComponentLayout
	... 77 more

```

**Comment by hasrat-ali** [comment]
Seems like you are using unofficial build (`pro.sketchwaree`). So this is not our problem.
