### ISSUE TITLE
Changing icon for app crash bug

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1556]
Sketchware Pro v7.0.0-SNAPSHOT-219ceff-minApi26 (150)
base.apk size: 126 MB (125906911 B)
Locale: en_US
SDK version: 34
Brand: samsung
Manufacturer: samsung
Model: SM-X700

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{pro.sketchwaree/pro.sketchwaree.activities.iconcreator.IconCreatorActivity}: android.view.InflateException: Binary XML file line #55 in pro.sketchwaree:layout/icon_creator_activity: Binary XML file line #55 in pro.sketchwaree:layout/icon_creator_activity: Error inflating class pro.sketchware.lib.iconcreator.PatternBackgroundView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4172)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4330)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.view.InflateException: Binary XML file line #55 in pro.sketchwaree:layout/icon_creator_activity: Binary XML file line #55 in pro.sketchwaree:layout/icon_creator_activity: Error inflating class pro.sketchware.lib.iconcreator.PatternBackgroundView
Caused by: android.view.InflateException: Binary XML file line #55 in pro.sketchwaree:layout/icon_creator_activity: Error inflating class pro.sketchware.lib.iconcreator.PatternBackgroundView
Caused by: java.lang.ClassNotFoundException: pro.sketchware.lib.iconcreator.PatternBackgroundView
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java:843)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:700)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at pro.sketchwaree.databinding.IconCreatorActivityBinding.inflate(IconCreatorActivityBinding.java:349)
	at pro.sketchwaree.databinding.IconCreatorActivityBinding.inflate(IconCreatorActivityBinding.java:343)
	at pro.sketchwaree.activities.iconcreator.IconCreatorActivity.onCreate(IconCreatorActivity.java:140)
	at android.app.Activity.performCreate(Activity.java:9001)
	at android.app.Activity.performCreate(Activity.java:8970)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4154)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4330)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.ClassNotFoundException: pro.sketchware.lib.iconcreator.PatternBackgroundView
	... 36 more

```

**Comment by RoyTheReal** [comment]
Fixed in one of the snapshots
