### ISSUE TITLE
Bug that does not allow deselecting the Library in Local Library

### ISSUE THREAD

**Issue by franciscowilton** [Sketchware-Pro/Sketchware-Pro#207]
Error in Sketchware:

![Screenshot_20210731-140829_Sketchware Pro](https://user-images.githubusercontent.com/60080154/127747615-677266fa-2c61-4668-95b8-7da73e78b28a.png)

Error in debug.txt:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at mod.agus.jcoderz.editor.manage.library.locallibrary.ManageLocalLibrary.getJarLocalLibrary(ManageLocalLibrary.java:198)
	at a.a.a.Dp.d(Dp.java:513)
	at a.a.a.Dp.f(Dp.java:736)
	at com.besome.sketch.design.DesignActivity$a.b(SourceFile:26)
	at a.a.a.MA.a(SourceFile:3)
	at a.a.a.MA.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

Demo video:

https://user-images.githubusercontent.com/60080154/127747686-337501ce-4e40-4ffe-be5d-a6a2444b5813.mp4

**Comment by RealNethical** [comment]
Yeah actually this happens.
Becuz when u select some libraries it has some folders and jar files. Those files paths are stored in a json file to use in the time of compiling. If u selected a library and later deleted its some files like manifest , res folder etc. Wen opening sketchware lib manager or compiling the project , sk will read the json file and look for the files in the json file . and cuz some files are deleted a compiling error or the project wont be able to delete the library . 

For modirs:
We could fix this by covering all the file and json task with with a try catch method and wen an error comes we can delete the json file , so the project wont show up errors

**Comment by JavkhlanK** [comment]
a599ba835eab6d1f81fb6df515612144663dadbd should stop that issue from occurring, but not in Local library Manager yet (as we've reverted it to v6.3.0 fix1's state)
