### ISSUE TITLE
The app shuts down when I want to import firebese setting from another project.

### ISSUE THREAD

**Issue by debendronath** [Sketchware-Pro/Sketchware-Pro#305]
![Screenshot_2022-01-12-01-11-16-209_com sketchware remod](https://user-images.githubusercontent.com/92230560/149006375-85e3a851-5fbe-4228-9c3d-3e3c393a8583.jpg)
![Screenshot_2022-01-12-01-11-35-050_com sketchware remod](https://user-images.githubusercontent.com/92230560/149006385-96529846-2724-4e22-8ccf-7131c37250ec.jpg)
![Screenshot_2022-01-12-01-11-37-766_com sketchware remod](https://user-images.githubusercontent.com/92230560/149006398-6105adcc-34d1-4c4e-8349-32f72b031738.jpg)

**Comment by JavkhlanK** [comment]
Unfortunately, that's a bug existing since vanilla Sketchware already. There is an open Pull request that'd fix this issue by replacing the Import button with one that'd import a Firebase configuration from a .json downloaded from Firebase Console, the same file Android Studio users would need.

**Comment by nasimpkrr** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.FF.TOUR.user.CheckoutActivity$Listview1Adapter.getView(CheckoutActivity.java:2330)
	at android.widget.AbsListView.obtainView(AbsListView.java:2402)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
	at android.widget.ListView.onMeasure(ListView.java:1323)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26488)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:462)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:762)
	at android.view.View.measure(View.java:26488)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4079)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2794)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3059)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2510)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9266)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1234)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
	at android.view.Choreographer.doCallbacks(Choreographer.java:902)
	at android.view.Choreographer.doFrame(Choreographer.java:835)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by shubham787320-star** [comment]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.lzr.mines.Main2Activity$7.onResponse(Main2Activity.java:280)
	at com.lzr.mines.RequestNetworkController$3$2.run(RequestNetworkController.java:179)
	at android.os.Handler.handleCallback(Handler.java:1014)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:250)
	at android.os.Looper.loop(Looper.java:340)
	at android.app.ActivityThread.main(ActivityThread.java:9928)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:625)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 12 more
