### ISSUE TITLE
Dynamically linked zipalign binary doesn't work on all devices

### ISSUE THREAD

**Issue by Htet04** [Sketchware-Pro/Sketchware-Pro#395]
When Compile

> a.a.a.By: WARNING: linker: "/data/data/com.sketchware.remod/cache/zipalign" unused DT entry: type 0x6fffe000 arg 0x19a0
WARNING: linker: "/data/data/com.sketchware.remod/cache/zipalign" unused DT entry: type 0x6fffe001 arg 0x30
WARNING: linker: "/data/data/com.sketchware.remod/cache/zipalign" unused DT entry: type 0x6fffe003 arg 0x8
CANNOT LINK EXECUTABLE "/data/user/0/com.sketchware.remod/cache/zipalign": cannot locate symbol "_ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev" referenced by "/data/data/com.sketchware.remod/cache/zipalign"...
	at a.a.a.Dp.runZipalign(Dp.java:1043)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1070)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:880)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by freindlytech** [comment]
I already fixed it but @JavkhlanK  revert my contribution if you want to fix it you can contact me

**Comment by JavkhlanK** [comment]
> I already fixed it but @JavkhlanK revert my contribution if you want to fix it you can contact me

Reverted because of untrusted binaries. Sorry, I don't want someone adding, for example, malware to Sketchware Pro. It's hard to verify if an already built binary is harmful or not.

**Comment by freindlytech** [comment]
@JavkhlanK  I didn't put any malware ok , that's not my work ok but I understand your issue , it's your choice.

**Comment by hasrat-ali** [comment]
Ok, but can you pls tell how you build those binaries?

**Comment by freindlytech** [comment]
@hasrat-ali  I already told you  You can take reference from termux aapt2 build

**Comment by Htet04** [comment]
So it wasn't my problem. Right?

**Comment by JavkhlanK** [comment]
> So it wasn't my problem. Right?

Definitely not yours. Maybe from your OEM.

**Comment by freindlytech** [comment]
> So it wasn't my problem. Right?

https://github.com/freindlytech/Sketchware-Pro check my repo build it and you can fix your error
