### ISSUE TITLE
Unable to import fonts

### ISSUE THREAD

**Issue by anthony-china** [Sketchware-Pro/Sketchware-Pro#424]
When I import fonts, the file format of TTF will be renamed toTMP format
![Uploading Screenshot_20220530_071358_bin.mt.plus.jpg…]()

**Comment by anthony-china** [comment]
The imported font will become a temporary file when running the software, resulting in the failure of software packaging.

**Comment by anthony-china** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.newproject14/com.my.newproject14.MainActivity}: java.lang.RuntimeException: Font asset not found fonts/asmmm_1.ttf
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.RuntimeException: Font asset not found fonts/asmmm_1.ttf
	at android.graphics.Typeface.createFromAsset(Typeface.java:990)
	at com.my.newproject14.MainActivity.initializeLogic(MainActivity.java:50)
	at com.my.newproject14.MainActivity.onCreate(MainActivity.java:42)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
	... 11 more

**Comment by JavkhlanK** [comment]
I had a feeling this was an issue. I hope it's possible to somehow know the MIME type of the picked file, else we can only support .ttf files (for now?).

**Comment by anthony-china** [comment]
This is another long repair

**Comment by anthony-china** [comment]
There seems to be no such problem before

**Comment by JamzApps** [comment]
> I had a feeling this was an issue. I hope it's possible to somehow know the MIME type of the picked file, else we can only support .ttf files (for now?).

There is with getType but it doesnt show actual .ttf, why not just use if getName substring length of minus 4 to length of equals .ttf, thats how i figure it out. So is there a workaround?

**Comment by JamzApps** [comment]
> Commit [6993bd1](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/6993bd102510dd4a498a6280b72e9bed1273e0c1) should have fixed this, it at least did in my case. Could you check if it now works for you too?

I use Document File, I havent set up File for SAF yet. If it works though it should be fine.

**Comment by anthony-china** [comment]
Let me try

**Comment by anthony-china** [comment]
That's right

**Comment by JavkhlanK** [comment]
@anthony-china so importing fonts works for you again too?

**Comment by anthony-china** [comment]
> @anthony-china所以导入字体也对你有用吗？
I downloaded the latest mobile version, tested it and found no problem! Thanks for fixing it so quickly!

**Comment by JavkhlanK** [comment]
> > @anthony-china所以导入字体也对你有用吗？
> > I downloaded the latest mobile version, tested it and found no problem! Thanks for fixing it so quickly!

Alright, thanks for confirming!
