### ISSUE TITLE
Sketchware ERROR!

### ISSUE THREAD

**Issue by mrarkjo** [Sketchware-Pro/Sketchware-Pro#540]
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at com.besome.sketch.editor.view.item.ItemHorizontalScrollView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25170)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25170)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25170)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25170)
	at androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:243)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
	at android.view.View.measure(View.java:25170)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25170)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(Unknown Source:262)
	at android.view.View.measure(View.java:25170)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:152)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6954)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:794)
	at android.view.View.measure(View.java:25170)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1933)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2242)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1811)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8127)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1054)
	at android.view.Choreographer.doCallbacks(Choreographer.java:877)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1039)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7631)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by ilyassesalama** [comment]
Can you write or record the steps to reproduce this error?

**Comment by PranavPurwar** [comment]
Even if a crash happens rarely, you should still try to fix it.

**Comment by JavkhlanK** [comment]
Let's track that in #563 instead.
