### ISSUE TITLE
New issue - Last Build github

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#568]
java.lang.StringIndexOutOfBoundsException: Index 62 out of bounds. length:47
	at io.github.rosemoe.sora.text.Content.checkIndex(Content.java:940)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:337)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:331)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawRows(EditorRenderer.java:856)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:515)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:173)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3688)
	at android.view.View.draw(View.java:22644)
	at android.view.View.draw(View.java:22506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4611)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4345)
	at android.view.View.draw(View.java:22504)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4611)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4345)
	at android.view.View.draw(View.java:22504)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4611)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4345)
	at android.view.View.draw(View.java:22504)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4611)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4345)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:2959)
	at android.view.View.draw(View.java:22647)
	at com.android.internal.policy.DecorView.draw(DecorView.java:899)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4668)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4576)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4247)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3470)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2266)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8846)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1473)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1270)
	at android.view.Choreographer.doFrame(Choreographer.java:981)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1458)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by JavkhlanK** [comment]
Can you give steps to reproduce that?

**Comment by AndroXStudiO** [comment]
what step?
when i remove text from sora-CodeEditor..then i got this error

**Comment by AndroXStudiO** [comment]
and this is suddenly not all time

**Comment by JavkhlanK** [comment]
Looks like a bug within the code editor itself. I'll check if there's been any bugfixes related to that in newer versions of it.

**Comment by JavkhlanK** [comment]
Looks like v0.17.0 fixes some occasional index out of bounds errors. We'll try to upgrade to it soon, but it will take some time as it didn't work immediately.

**Comment by JavkhlanK** [comment]
Upgraded to v0.17.2 recently, should've been fixed.
