### ISSUE TITLE
New SnapShort version error

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#613]
android.view.InflateException: Binary XML file line #3 in com.sketchware.remod:layout/view_item_local_lib: addView(View, LayoutParams) is not supported in AdapterView
Caused by: java.lang.UnsupportedOperationException: addView(View, LayoutParams) is not supported in AdapterView
	at android.widget.AdapterView.addView(AdapterView.java:535)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:689)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at dev.aldi.sayuti.editor.manage.ManageLocalLibraryActivity$LibraryAdapter.getView(ManageLocalLibraryActivity.java:139)
	at android.widget.AbsListView.obtainView(AbsListView.java:2435)
	at android.widget.ListView.makeAndAddView(ListView.java:2082)
	at android.widget.ListView.fillDown(ListView.java:799)
	at android.widget.ListView.fillFromTop(ListView.java:861)
	at android.widget.ListView.layoutChildren(ListView.java:1816)
	at android.widget.AbsListView.onLayout(AbsListView.java:2232)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1822)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:873)
	at android.view.View.layout(View.java:23154)
	at android.view.ViewGroup.layout(ViewGroup.java:6497)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3272)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2266)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8846)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1473)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1270)
	at android.view.Choreographer.doFrame(Choreographer.java:981)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1458)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by JavkhlanK** [comment]
Whoops. Missed testing the last few changes out. Thanks for reporting, I'll fix this in a minute.
