### ISSUE TITLE
See new error

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#650]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setTag(java.lang.Object)' on a null object reference
	at com.besome.sketch.editor.view.ViewPane.g(Unknown Source:30)
	at com.besome.sketch.editor.view.ViewEditor.e(Unknown Source:2)
	at a.a.a.jr.c(jr.java:209)
	at a.a.a.jr.a(jr.java:150)
	at a.a.a.jr$$ExternalSyntheticLambda2.a(Unknown Source:2)
	at com.besome.sketch.editor.view.ViewProperty.selectView(ViewProperty.java:267)
	at com.besome.sketch.editor.view.ViewProperty.-$$Nest$mselectView(Unknown Source:0)
	at com.besome.sketch.editor.view.ViewProperty$1.onItemSelected(ViewProperty.java:251)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:977)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:966)
	at android.widget.AdapterView.access$300(AdapterView.java:59)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:930)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by JavkhlanK** [comment]
Please also tell steps to reproduce that error, or even better, a screen recording when you upload stack traces here. If you can't, just use the in-app Send crash report button instead, please.
