### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#651]
java.lang.NullPointerException: Attempt to invoke interface method 'com.besome.sketch.beans.ViewBean a.a.a.sy.getBean()' on a null object reference
	at com.besome.sketch.editor.view.ViewPane.a(Unknown Source:3)
	at com.besome.sketch.editor.view.ViewPane.d(Unknown Source:83)
	at com.besome.sketch.editor.view.ViewEditor.b(Unknown Source:26)
	at com.besome.sketch.editor.view.ViewEditor.onTouch(Unknown Source:1052)
	at android.view.View.dispatchTouchEvent(View.java:14477)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3167)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1901)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4207)
	at a.a.a.pa.dispatchTouchEvent(Unknown Source:2)
	at a.a.a.pa.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:523)
	at android.view.View.dispatchPointerEvent(View.java:14747)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6603)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6380)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5810)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5874)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5833)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6019)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5841)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6076)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5814)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5874)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5833)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5841)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5814)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8745)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8696)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8649)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8889)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loop(Looper.java:199)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by JavkhlanK** [comment]
Same thing as in #650.
