### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DevAnDroidCoder** [Sketchware-Pro/Sketchware-Pro#695]
When Visiting source code like following I get error I get this error only when there is double comment
`/*
/*
 = new Gson().fromJson("", new TypeToken<ArrayList<String>>(){}.getType());
lm = new Gson().fromJson("", new TypeToken<ArrayList<HashMap<String, Object>>>(){}.getType());
*/
_processdialog(false, "");
ytData = new HashMap<>();
ytData = new Gson().
title.setText((HashMap<String,Object>)(ArrayList<HashMap<String,Object>>)ytData.get("items").get((int)(0)).get("snippet").get("title").toString());
ytData.clear();
*/`
Error : 
`java.lang.ArrayIndexOutOfBoundsException: length=426; index=426
	at a.a.a.Lx.j(Lx.java:3132)
	at com.besome.sketch.editor.LogicEditorActivity.showSourceCode(LogicEditorActivity.java:2890)
	at com.besome.sketch.editor.LogicEditorActivity.onOptionsItemSelected(LogicEditorActivity.java:2407)
	at android.app.Activity.onMenuItemSelected(Activity.java:4203)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(Unknown Source:0)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(Unknown Source:0)
	at a.a.a.pa.onMenuItemSelected(Unknown Source:2)
	at a.a.a.pa.onMenuItemSelected(Unknown Source:2)
	at a.a.a.O.onMenuItemClick(Unknown Source:5)
	at a.a.a.Yb.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.widget.ActionMenuView$c.a(Unknown Source:6)
	at a.a.a.Ba.a(Unknown Source:4)
	at a.a.a.Fa.g(Unknown Source:14)
	at a.a.a.Ba.a(Unknown Source:12)
	at a.a.a.Ba.a(Unknown Source:1)
	at androidx.appcompat.widget.ActionMenuView.a(Unknown Source:3)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7184)
	at android.view.View.performClickInternal(View.java:7157)
	at android.view.View.access$3500(View.java:821)
	at android.view.View$PerformClick.run(View.java:27660)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
`

**Comment by JavkhlanK** [comment]
Which Sketchware Pro version did you use? Should already be fixed with recent snapshot builds.

**Comment by TechnicalStudioDevelopers** [comment]
> Which Sketchware Pro version did you use? Should already be fixed with recent snapshot builds.

Latest version : Version v6.4.0-rc05-minApi26

**Comment by JavkhlanK** [comment]
This bug was already fixed then. Nonetheless, thanks for reporting.
