### ISSUE TITLE
Component Manager Error

### ISSUE THREAD

**Issue by A2A410** [Sketchware-Pro/Sketchware-Pro#697]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at mod.hilal.saif.activities.tools.ComponentsMaker$ListAdapter.getView(ComponentsMaker.java:216)
	at android.widget.AbsListView.obtainView(AbsListView.java:2452)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1426)
	at android.widget.ListView.onMeasure(ListView.java:1332)
	at android.view.View.measure(View.java:24979)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24979)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
	at android.view.View.measure(View.java:24979)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24979)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24979)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:783)
	at android.view.View.measure(View.java:24979)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3489)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2165)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2469)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2049)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8446)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
	at android.view.Choreographer.doFrame(Choreographer.java:807)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

-- It happens after i tried importing a json block

**Comment by A2A410** [comment]
Fixed it, by deleting a file from /storage/emulated/0/.sketchware/data/system
