### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#701]
java.io.IOException: proguard.ParseException: Expecting class path separator ':' before '/classes.jar' in argument number 70
	at a.a.a.Dp.runProguard(Dp.java:967)
	at mod.hey.studios.project.proguard.ProguardHandler.start(ProguardHandler.java:216)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1052)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: proguard.ParseException: Expecting class path separator ':' before '/classes.jar' in argument number 70
	at proguard.ConfigurationParser.parseClassPathArgument(ConfigurationParser.java:449)
	at proguard.ConfigurationParser.parse(ConfigurationParser.java:156)
	at a.a.a.Dp.runProguard(Dp.java:965)
	... 11 more

**Comment by subhash16** [comment]
[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/10398684/debug.txt)

**Comment by JavkhlanK** [comment]
Thanks!

**Comment by subhash16** [comment]
When will this problem solv

**Comment by JavkhlanK** [comment]
I'll try to work on it, but can't give any time estimations at all (as always)

**Comment by subhash16** [comment]
Ok Sir

**Comment by subhash16** [comment]
Sir could you tell me why the app size increase when enable appcompat & admob it increases 7 mb

**Comment by JavkhlanK** [comment]
Enabling them adds new libraries. Libraries aren't 0 bytes large, they just are those 7 MB large.

**Comment by subhash16** [comment]
Not solving

**Comment by JavkhlanK** [comment]
why close the issue?

**Comment by subhash16** [comment]
I will not report anymore
