### ISSUE TITLE
Suddenly i got this error - last Snapshot version

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#709]
java.lang.RuntimeException: Undefined Prefix: amdroid in com.android.org.kxml2.io.KXmlParser@92e2db7
	at com.android.org.kxml2.io.KXmlParser.adjustNsp(KXmlParser.java:262)
	at com.android.org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1167)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:380)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
	at a.a.a.Ox.readAttributesToReplace(Ox.java:874)
	at a.a.a.Ox.writeWidget(Ox.java:240)
	at a.a.a.Ox.writeWidget(Ox.java:369)
	at a.a.a.Ox.writeWidget(Ox.java:369)
	at a.a.a.Ox.writeRootLayout(Ox.java:110)
	at a.a.a.Ox.a(Ox.java:230)
	at a.a.a.yq.a(yq.java:716)
	at a.a.a.yq.b(yq.java:635)
	at a.a.a.yq.b(yq.java:628)
	at com.besome.sketch.design.DesignActivity.generateProjectDebugFiles(DesignActivity.java:214)
	at com.besome.sketch.design.DesignActivity.-$$Nest$mgenerateProjectDebugFiles(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1002)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1175)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:927)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by AndroXStudiO** [comment]
![Screenshot_2023-01-16-16-10-04-05_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/212653050-2ed767cf-f40c-45bb-bcb9-639072222ca5.jpg)

Sorry, Here is my mistake i Write "Amdroid" 🤦‍♂️ it should be "android"

**Comment by AndroXStudiO** [comment]
![IMG_20230116_161250](https://user-images.githubusercontent.com/88816748/212653501-9c8be56c-3cfe-4d36-81db-53d75366de66.jpg)
Sorry, Here is my mistake... It should be "Android"

**Comment by JavkhlanK** [comment]
The app shouldn't crash though!

**Comment by JavkhlanK** [comment]
The app shouldn't crash anymore.
