### ISSUE TITLE
Crash when using kotlin library

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#714]
I'm trying to use https://github.com/massoudss/waveformSeekBar
But app get crash. Error text ->
java.lang.NoSuchMethodError: No static method maxOrNull([I)Ljava/lang/Integer; in class Lkotlin/collections/ArraysKt; or its super classes (declaration of 'kotlin.collections.ArraysKt' appears in base.apk!classes58.dex)
	at ir.amirsina.lyricm.WaveformSeekBar.setMaxValue(WaveformSeekBar.kt:205)
	at ir.amirsina.lyricm.WaveformSeekBar.setSample(WaveformSeekBar.kt:44)
	at ir.amirsina.lyricm.WaveformSeekBar$setSampleFrom$1.invoke(WaveformSeekBar.kt:221)
	at ir.amirsina.lyricm.WaveformSeekBar$setSampleFrom$1.invoke(WaveformSeekBar.kt:220)
	at ir.amirsina.lyricm.utils.WaveformOptions.handleAmplitudaOutput(WaveformOptions.kt:33)
	at ir.amirsina.lyricm.utils.WaveformOptions.getSampleFrom(WaveformOptions.kt:13)
	at ir.amirsina.lyricm.WaveformSeekBar.setSampleFrom(WaveformSeekBar.kt:220)
	at ir.amirsina.lyricm.LyricsMakeActivity.initializeLogic(LyricsMakeActivity.java:82)
	at ir.amirsina.lyricm.LyricsMakeActivity.onCreate(LyricsMakeActivity.java:60)
	at android.app.Activity.performCreate(Activity.java:8093)
	at android.app.Activity.performCreate(Activity.java:8067)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3651)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by PranavPurwar** [comment]
Probably you don't have kotlin stdlib on classpath or the library doesn't support the stdlib version that sketchware pro uses

**Comment by AmirSinaRZ** [comment]
So what is the solution?

**Comment by subhash16** [comment]
Also I need the solution

**Comment by PranavPurwar** [comment]
> So what is the solution?

add kotlin stdlib to libraries or just add a kotlin class in `Java/Kotlin Manager`

> It will automatically stdlib on libs if you do so

**Comment by AmirSinaRZ** [comment]
Solved
