### ISSUE TITLE
All projects crashed

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#735]
I downloaded last snapshot ([Snapshot](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/4038607164) ) and my all projects keep crashing while running.

[Vedio Link](https://dl.dropbox.com/s/00ibmn75zz0n4wl/Sketchware%20Pro.mp4?dl=0)

**Comment by TechnicalStudioDevelopers** [comment]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Throwable
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask$1.handleMessage(DesignActivity.java:949)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by JavkhlanK** [comment]
You got a wrong snapshot build. [You'd want this one](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/4038564047).

To prevent that from happening again, watch out to get the latest snapshot build only from branch main. That means it has to say `main` in blue next to the commit name.

**Comment by JavkhlanK** [comment]
Fixed with commit 15b2d3b7e1d954b6ebee8c96224ed695f4dbe30b.
