### ISSUE TITLE
Problem deleting MoreBlocks

### ISSUE THREAD

**Issue by SyntaxGalaxy** [Sketchware-Pro/Sketchware-Pro#739]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
	at a.a.a.eC.n(Unknown Source:79)
	at a.a.a.rs.deleteMoreBlock(rs.java:255)
	at a.a.a.rs.-$$Nest$mdeleteMoreBlock(Unknown Source:0)
	at a.a.a.rs$EventAdapter$ViewHolder.lambda$new$0$a-a-a-rs$EventAdapter$ViewHolder(rs.java:957)
	at a.a.a.rs$EventAdapter$ViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7184)
	at android.view.View.performClickInternal(View.java:7157)
	at android.view.View.access$3500(View.java:821)
	at android.view.View$PerformClick.run(View.java:27660)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by JavkhlanK** [comment]
Some More Block(s) is/are broken in your project.

**Comment by TechnicalStudioDevelopers** [comment]
> Some More Block(s) is/are broken in your project.

I created new more block and just deleted and this error appeared

**Comment by TechnicalStudioDevelopers** [comment]
> Some More Block(s) is/are broken in your project.

I created new more block and just deleted and this error appeared

**Comment by TechnicalStudioDevelopers** [comment]
[Video](https://www.dropbox.com/s/00ibmn75zz0n4wl/Sketchware%20Pro.mp4?dl=0)

**Comment by araafroyall** [comment]
Possible solution


The NullPointerException in this case is being caused by calling the containsKey() method on a null HashMap object. Specifically, the error occurs in the method deleteMoreBlock in the rs class, likely on a HashMap that is not initialized before trying to access it.

To resolve this:

1. Check for Null HashMap: Ensure that the HashMap is initialized before calling any methods on it. Before checking if a key exists in the map, you can add a null check to avoid invoking containsKey on a null object:

Example:

```java
if (yourHashMap != null && yourHashMap.containsKey(someKey)) {
    // Perform your logic here
} else {
    // Handle the null case (e.g., initialize the map or show an error)
}
```


2. Initialize HashMap: If the HashMap is supposed to be initialized but hasn't been, make sure it's being properly instantiated before use. For example:

```java
HashMap<String, Object> yourHashMap = new HashMap<>();
```

If the map is expected to be populated later, ensure that it is initialized early in the code flow.


3. Debug the Data Flow: If the HashMap is passed from another part of the code, verify that the data is properly initialized and passed to the method before calling containsKey().


4. Safe Initialization: If you want to ensure the HashMap is always initialized, you can initialize it with an empty map when it's not yet set:

```java
HashMap<String, Object> yourHashMap = new HashMap<>();  // Empty map
```



By ensuring that the HashMap is initialized before using it, this NullPointerException can be prevented.

**Comment by JavkhlanK** [comment]
@araafroyall please stop with commenting useless outputs of ChatGPT or other AI tools, no maintainer here needed an explanation on what an NPE is. please, just don't use any AI tools for comments like this, rely on your own skills instead.

**Comment by araafroyall** [comment]
okkk
