### ISSUE TITLE
Erreur when exporting

### ISSUE THREAD

**Issue by GymoFit** [Sketchware-Pro/Sketchware-Pro#740]
I was able to export my app but when i downloaded this version it say this:

java.lang.NoSuchFieldError: No instance field t of type Ljava/util/ArrayList; in class La/a/a/jq; or its superclasses (declaration of 'a.a.a.jq' appears in /data/app/~~Awo5HaqaqBpc5tTuHHvVvw==/com.sketchware.remod-9OK_jmDQ9mRUppczMm-kPg==/base.apk!classes20.dex)
	at a.a.a.Fx.a(Unknown Source:10039)
	at a.a.a.Fx.a(Unknown Source:19)
	at a.a.a.Fx.a(Unknown Source:16862)
	at a.a.a.Fx.a(Unknown Source:19)
	at a.a.a.Fx.a(Unknown Source:16862)
	at a.a.a.Fx.a(Unknown Source:19)
	at a.a.a.Fx.a(Unknown Source:16862)
	at a.a.a.Fx.a(Unknown Source:19)
	at a.a.a.Fx.a(Unknown Source:16862)
	at a.a.a.Fx.a(Unknown Source:62)
	at a.a.a.Jx.handleAppCompat(Jx.java:789)
	at a.a.a.Jx.generateCode(Jx.java:178)
	at a.a.a.yq.a(yq.java:828)
	at a.a.a.yq.b(yq.java:759)
	at a.a.a.yq.b(yq.java:752)
	at com.besome.sketch.design.DesignActivity.generateProjectDebugFiles(DesignActivity.java:218)
	at com.besome.sketch.design.DesignActivity.-$$Nest$mgenerateProjectDebugFiles(Unknown Source:0)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:973)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1152)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:895)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by AbrishPhoenix** [comment]
the same here

**Comment by JavkhlanK** [comment]
This bug was already fixed with Sketchware Pro v6.4.0-rc05.
