### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [Sketchware-Pro/Sketchware-Pro#761]
```java
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at com.besome.sketch.editor.view.item.ItemVerticalScrollView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24834)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24834)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24834)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24834)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24834)
	at androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:243)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
	at android.view.View.measure(View.java:24834)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24834)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24834)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(Unknown Source:262)
	at android.view.View.measure(View.java:24834)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:152)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6975)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:773)
	at android.view.View.measure(View.java:24834)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3237)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1994)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2297)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1882)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8047)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:860)
	at android.view.Choreographer.doFrame(Choreographer.java:785)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**Comment by JavkhlanK** [comment]
Duplicate of #563.
