### ISSUE TITLE
Getting error when merging library dex files in Sketchware Pro latest remod

### ISSUE THREAD

**Issue by COMDroid** [Sketchware-Pro/Sketchware-Pro#85]
Getting error when merging library dex files in sketchware pro latest remode.

When i use some libraries together it's getting a error.

Error:
field ID not in [0, 0xffff]: 65536

**Comment by hasrat-ali** [comment]
Can you send the Error Log

**Comment by COMDroid** [comment]
**This is log i captured from logcat reader**

`mod.agus.jcoderz.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
	at mod.agus.jcoderz.dx.merge.DexMerger$5.updateIndex(DexMerger.java:372)
	at mod.agus.jcoderz.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:1046)
	at mod.agus.jcoderz.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:381)
	at mod.agus.jcoderz.dx.merge.DexMerger.mergeDexes(DexMerger.java:190)
	at mod.agus.jcoderz.dx.merge.DexMerger.merge(DexMerger.java:218)
	at a.a.a.Dp.mergeDexes(Dp.java:788)
	at a.a.a.Dp.dexLibraries(Dp.java:455)
	at a.a.a.Dp.a(Dp.java:162)
	at a.a.a.Dp.h(Dp.java:658)
	at com.besome.sketch.design.DesignActivity$a.b(DesignActivity.java:1164)
	at a.a.a.MA.a(SourceFile:3)
	at com.besome.sketch.design.DesignActivity$a.doInBackground(DesignActivity.java:1273)
	at com.besome.sketch.design.DesignActivity$a.doInBackground(DesignActivity.java:1039)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)`

**Comment by COMDroid** [comment]
**This is debug.txt from sketchware**
[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/6357748/debug.txt)

**Comment by COMDroid** [comment]
**This is error showed in sketchware**

![Screenshot_20210422-163558](https://user-images.githubusercontent.com/83010449/115704294-d3400500-a388-11eb-96df-c514fedb0c4f.png)

**Comment by JavkhlanK** [comment]
Which libraries did you use?

**Comment by COMDroid** [comment]
I am using

Firebase components.
uk.co.barbuzz:beerprogressview:0.0.6
com.nineoldandroids:library:2.4.0
com.razorpay.checkout:1.6.7
Google IN APP UPDATE Library

When using this libraries app will build successfully.

When i adding one of below library getting error
com.mindorks.android:prdownloader:0.6.0
android.support.v4

**Comment by hasrat-ali** [comment]
.

**Comment by hasrat-ali** [comment]
Mr. @COMDroid,
Maybe your last two libraries are corrupted,
try to re-download you libraries and try again.

If you get it again, then we will take some action.

**Comment by COMDroid** [comment]
Ok bro

**Comment by ILY4553** [comment]
This issue happens when you download a library with Dx, it has a bug. You can download libs with R8 currently.

**Comment by PranavPurwar** [comment]
idea: add `wontfix` label and close this issue

**Comment by JavkhlanK** [comment]
This exact issue should've been fixed already, as v6.3.0 fix1's DEX merge logic only checked for method IDs, and not, let's say, field IDs.
