### ISSUE TITLE
Some compile assets sometimes missing due to being in cache files

### ISSUE THREAD

**Issue by CarlosCMD** [Sketchware-Pro/Sketchware-Pro#862]
Here's the snippet;

a.a.a.By: java.io.FileNotFoundException: /data/user/0/com.sketchware.remod/cache/libs/dexs/appcompat-1.4.0.dex does not exist
	at a.a.a.Dp.buildApk(Dp.java:622)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1073)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by JavkhlanK** [comment]
Yeah, the bug's that some cache files get deleted and Sketchware Pro isn't detecting that currently. Clear all cache files and then it should work again. Having enough free storage space should normally stop these issues from happening.

**Comment by CarlosCMD** [comment]
Its solved but now am getting;

a.a.a.By: Failed to add /storage/emulated/0/.sketchware/libs/local_libs/Android Support /classes.jar
	at a.a.a.Dp.buildApk(Dp.java:622)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1073)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by JavkhlanK** [comment]
@CarlosCMD that's a different, unrelated issue. See #864 for details.

**Comment by JavkhlanK** [comment]
Let's keep this open until the bug is fixed.

**Comment by JavkhlanK** [comment]
fixed by 4374b3c955aabe5e14015d790047174e4c18a9f4

**Comment by lorenzohappy19** [comment]
The cache is empty, what do I do
