### ISSUE TITLE
Unexpectedly error 🥲

When I'm undo the widgets, to show error

### ISSUE THREAD

**Issue by Ars-king** [Sketchware-Pro/Sketchware-Pro#882]
Error log //

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setTag(java.lang.Object)' on a null object reference
	at com.besome.sketch.editor.view.ViewPane.g(Unknown Source:30)
	at com.besome.sketch.editor.view.ViewEditor.e(Unknown Source:2)
	at a.a.a.jr.m(Unknown Source:157)
	at a.a.a.jr.onOptionsItemSelected(Unknown Source:8)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Unknown Source:13)
	at a.a.a.dg.b(Unknown Source:26)
	at a.a.a.Vf.b(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(Unknown Source:24)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(Unknown Source:0)
	at a.a.a.pa.onMenuItemSelected(Unknown Source:2)
	at a.a.a.pa.onMenuItemSelected(Unknown Source:2)
	at a.a.a.O.onMenuItemClick(Unknown Source:5)
	at a.a.a.Yb.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.widget.ActionMenuView$c.a(Unknown Source:6)
	at a.a.a.Ba.a(Unknown Source:4)
	at a.a.a.Fa.g(Unknown Source:14)
	at a.a.a.Ba.a(Unknown Source:12)
	at a.a.a.Ba.a(Unknown Source:1)
	at androidx.appcompat.widget.ActionMenuView.a(Unknown Source:3)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7535)
	at android.view.View.performClickInternal(View.java:7512)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29488)
	at android.os.Handler.handleCallback(Handler.java:984)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

**Comment by JavkhlanK** [comment]
Let's track that in #650. Could you tell steps to reproduce that error, or even better, show a screen recording in that other Issue?
