### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#936]
Type org.jetbrains.kotlin.cli.jvm.javac.MessageCollectorAdapter is defined multiple times: G:\StudioProjects\Sketchware-Pro\kotlinc\build\.transforms\120f4a36fbdd81cb7d930870a1c27112\transformed\main\main_dex\classes.dex, G:\StudioProjects\Sketchware-Pro\app\build\intermediates\external_libs_dex\minApi26Release\mergeExtDexMinApi26Release\classes7.dex

**Comment by JavkhlanK** [comment]
dude you need to show *entire* error messages instead of just snippets that are useless on their own

**Comment by Win-one** [comment]
> Task :app:mergeDexMinApi26Release FAILED
AGPBI: {"kind":"error","text":"Type org.jetbrains.kotlin.cli.jvm.javac.MessageCollectorAdapter is defined multiple times: G:\\StudioProjects\\Sketchware-Pro\\kotlinc\\build\\.transforms\\120f4a36fbdd81cb7d930870a1c27112\\transformed\\main\\main_dex\\classes.dex, G:\\StudioProjects\\Sketchware-Pro\\app\\build\\intermediates\\external_libs_dex\\minApi26Release\\mergeExtDexMinApi26Release\\classes7.dex","sources":[{"file":"G:\\StudioProjects\\Sketchware-Pro\\kotlinc\\build\\.transforms\\120f4a36fbdd81cb7d930870a1c27112\\transformed\\main\\main_dex\\classes.dex"}],"tool":"D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Type org.jetbrains.kotlin.cli.jvm.javac.MessageCollectorAdapter is defined multiple times: G:\StudioProjects\Sketchware-Pro\kotlinc\build\.transforms\120f4a36fbdd81cb7d930870a1c27112\transformed\main\main_dex\classes.dex, G:\StudioProjects\Sketchware-Pro\app\build\intermediates\external_libs_dex\minApi26Release\mergeExtDexMinApi26Release\classes7.dex
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
	at com.android.builder.dexing.D8DexArchiveMerger.getMergingExceptionToRethrow(D8DexArchiveMerger.java:159)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:147)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:893)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:837)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:169)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:114)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: G:\StudioProjects\Sketchware-Pro\kotlinc\build\.transforms\120f4a36fbdd81cb7d930870a1c27112\transformed\main\main_dex\classes.dex
	at Version.fakeStackEntry(Version_8.0.46.java:0)
	at com.android.tools.r8.utils.N0.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:74)
	at com.android.tools.r8.utils.N0.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:27)
	at com.android.tools.r8.utils.N0.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:26)
	at com.android.tools.r8.utils.N0.b(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:2)
	at com.android.tools.r8.D8.run(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:145)
	... 38 more
Caused by: com.android.tools.r8.utils.b: Type org.jetbrains.kotlin.cli.jvm.javac.MessageCollectorAdapter is defined multiple times: G:\StudioProjects\Sketchware-Pro\kotlinc\build\.transforms\120f4a36fbdd81cb7d930870a1c27112\transformed\main\main_dex\classes.dex, G:\StudioProjects\Sketchware-Pro\app\build\intermediates\external_libs_dex\minApi26Release\mergeExtDexMinApi26Release\classes7.dex
	at com.android.tools.r8.utils.E2.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:21)
	at com.android.tools.r8.utils.E2.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:26)
	at com.android.tools.r8.utils.r2.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:44)
	at com.android.tools.r8.utils.r2.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
	at com.android.tools.r8.utils.r2.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:6)
	at com.android.tools.r8.graph.k4$a.e(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:7)
	at com.android.tools.r8.dex.c.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:58)
	at com.android.tools.r8.dex.c.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:9)
	at com.android.tools.r8.dex.c.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:8)
	at com.android.tools.r8.D8.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:29)
	at com.android.tools.r8.D8.d(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:17)
	at com.android.tools.r8.D8.b(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:1)
	at com.android.tools.r8.utils.N0.a(R8_8.0.46_2ffa4e0571e5ebfa8c3310c54d5dda57b06b7af8069dc742e901fe496c3e13dd:23)
	... 41 more


> Task :app:lintVitalReportMinApi26Release
> Task :app:lintVitalMinApi26Release

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexMinApi26Release'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Type org.jetbrains.kotlin.cli.jvm.javac.MessageCollectorAdapter is defined multiple times: G:\StudioProjects\Sketchware-Pro\kotlinc\build\.transforms\120f4a36fbdd81cb7d930870a1c27112\transformed\main\main_dex\classes.dex, G:\StudioProjects\Sketchware-Pro\app\build\intermediates\external_libs_dex\minApi26Release\mergeExtDexMinApi26Release\classes7.dex
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

**Comment by hasrat-ali** [comment]
Can you try to clean and rebuild the project?

**Comment by JavkhlanK** [comment]
maybe try getting the latest code from the repo, this kind of error never occurred to me nor the CI

**Comment by Win-one** [comment]
When I deleted"javacLogger.kt"It worked！

**Comment by PranavPurwar** [comment]
> maybe try getting the latest code from the repo, this kind of error never occurred to me nor the CI

release builds check for duplicate classes in code while debug build just puts duplicated bytecode in dex files

**Comment by PranavPurwar** [comment]
> When I deleted"javacLogger.kt"It worked！

Great, now try to build a projects which uses kotlin and it will fail

**Comment by hasrat-ali** [comment]
Now all duplicate classes are removed afaik.
