### ISSUE TITLE
Old Library androidx

### ISSUE THREAD

**Issue by appt2** [Sketchware-Pro/Sketchware-Pro#963]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.strings.translator/com.strings.translator.MainActivity}: android.view.InflateException: Binary XML file line #14 in com.strings.translator:layout/main: Binary XML file line #14 in com.strings.translator:layout/main: Error inflating class com.google.android.material.materialswitch.MaterialSwitch
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.view.InflateException: Binary XML file line #14 in com.strings.translator:layout/main: Binary XML file line #14 in com.strings.translator:layout/main: Error inflating class com.google.android.material.materialswitch.MaterialSwitch
Caused by: android.view.InflateException: Binary XML file line #14 in com.strings.translator:layout/main: Error inflating class com.google.android.material.materialswitch.MaterialSwitch
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:883)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1035)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at com.strings.translator.MainActivity.onCreate(MainActivity.java:72)
	at android.app.Activity.performCreate(Activity.java:8538)
	at android.app.Activity.performCreate(Activity.java:8502)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NoSuchMethodError: No static method getUncheckedState([I)[I in class Lcom/google/android/material/drawable/DrawableUtils; or its super classes (declaration of 'com.google.android.material.drawable.DrawableUtils' appears in /data/app/~~jF6NiSIPHEG4bt8K6jPBmw==/com.strings.translator-eje_Ee8qf-91YhauJYyz1w==/base.apk!classes37.dex)
	at com.google.android.material.materialswitch.MaterialSwitch.onCreateDrawableState(MaterialSwitch.java:141)
	at android.view.View.getDrawableState(View.java:24584)
	at android.widget.TextView.updateTextColors(TextView.java:6132)
	at android.widget.TextView.setTextColor(TextView.java:5155)
	at android.widget.TextView.applyTextAppearance(TextView.java:4238)
	at android.widget.TextView.<init>(TextView.java:1733)
	at android.widget.Button.<init>(Button.java:166)
	at android.widget.CompoundButton.<init>(CompoundButton.java:104)
	at android.widget.CompoundButton.<init>(CompoundButton.java:100)
	at androidx.appcompat.widget.SwitchCompat.<init>(SwitchCompat.java:247)
	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:82)
	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:78)
	... 31 more
```

Hello, I tested the latest apk output action and added a widget from the Google Material library and received this error!!

**Comment by JavkhlanK** [comment]
share your project as .swb or list enabled Local libraries

**Comment by appt2** [comment]
@JavkhlanK can you send id Tel?

**Comment by JavkhlanK** [comment]
i'm [\@jkhon0](https://t.me/jkhon0) there

**Comment by appt2** [comment]
We could not find your ID. Message me on Telegram. My ID is @appt2Comery

**Comment by JavkhlanK** [comment]
my bad, see again

**Comment by appt2** [comment]
> my bad, see again

now sending massges from tel see pv

**Comment by JavkhlanK** [comment]
that project you sent contains MDC v1.10.0-alpha03 as Local library but also has AppCompat turned on. AppCompat contains the MDC library itself, but you can't have both at the same time. You have to exclude the built-in library version using the feature described further in #696
